/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.controllers;

import app.zuplo.tesserplatformv1pull51me98e48a7.ApiHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.Server;
import app.zuplo.tesserplatformv1pull51me98e48a7.exceptions.ApiException;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.request.HttpMethod;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.AccountListResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.AccountResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.CreateBankRequest;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.CreateBankResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.CreateWalletRequest;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.CreateWalletResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.Type4Enum;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.UpdateAccountRequest;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.UpdateAccountResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AccountsController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public AccountsController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Retrieve all accounts (both bank and wallet accounts) for your workspace.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  type  Optional parameter: Filter by account type
     * @param  tenantId  Optional parameter: Filter by tenant ID. At most one of tenant_id or
     *         counterparty_id may be provided.
     * @param  counterpartyId  Optional parameter: Filter by counterparty ID. At most one of
     *         tenant_id or counterparty_id may be provided.
     * @param  includeSensitive  Optional parameter: If true, includes sensitive fields like
     *         bank_account_number.
     * @return    Returns the AccountListResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public AccountListResponse findAll(
            final String authorization,
            final Type4Enum type,
            final String tenantId,
            final String counterpartyId,
            final Boolean includeSensitive) throws ApiException, IOException {
        return prepareFindAllRequest(authorization, type, tenantId, counterpartyId,
                includeSensitive).execute();
    }

    /**
     * Retrieve all accounts (both bank and wallet accounts) for your workspace.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  type  Optional parameter: Filter by account type
     * @param  tenantId  Optional parameter: Filter by tenant ID. At most one of tenant_id or
     *         counterparty_id may be provided.
     * @param  counterpartyId  Optional parameter: Filter by counterparty ID. At most one of
     *         tenant_id or counterparty_id may be provided.
     * @param  includeSensitive  Optional parameter: If true, includes sensitive fields like
     *         bank_account_number.
     * @return    Returns the AccountListResponse response from the API call
     */
    public CompletableFuture<AccountListResponse> findAllAsync(
            final String authorization,
            final Type4Enum type,
            final String tenantId,
            final String counterpartyId,
            final Boolean includeSensitive) {
        try {
            return prepareFindAllRequest(authorization, type, tenantId, counterpartyId,
            includeSensitive).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for findAll.
     */
    private ApiCall<AccountListResponse, ApiException> prepareFindAllRequest(
            final String authorization,
            final Type4Enum type,
            final String tenantId,
            final String counterpartyId,
            final Boolean includeSensitive) {
        return new ApiCall.Builder<AccountListResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/accounts")
                        .queryParam(param -> param.key("type")
                                .value((type != null) ? type.value() : null).isRequired(false))
                        .queryParam(param -> param.key("tenant_id")
                                .value(tenantId).isRequired(false))
                        .queryParam(param -> param.key("counterparty_id")
                                .value(counterpartyId).isRequired(false))
                        .queryParam(param -> param.key("include_sensitive")
                                .value(includeSensitive).isRequired(false))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, AccountListResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Create a new fiat bank account.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter: Bank account details
     * @return    Returns the CreateBankResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public CreateBankResponse createBank(
            final String authorization,
            final CreateBankRequest body) throws ApiException, IOException {
        return prepareCreateBankRequest(authorization, body).execute();
    }

    /**
     * Create a new fiat bank account.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter: Bank account details
     * @return    Returns the CreateBankResponse response from the API call
     */
    public CompletableFuture<CreateBankResponse> createBankAsync(
            final String authorization,
            final CreateBankRequest body) {
        try {
            return prepareCreateBankRequest(authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for createBank.
     */
    private ApiCall<CreateBankResponse, ApiException> prepareCreateBankRequest(
            final String authorization,
            final CreateBankRequest body) {
        return new ApiCall.Builder<CreateBankResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/accounts/banks")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, CreateBankResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Create a new stablecoin wallet account.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter: Wallet account details
     * @return    Returns the CreateWalletResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public CreateWalletResponse createWallet(
            final String authorization,
            final CreateWalletRequest body) throws ApiException, IOException {
        return prepareCreateWalletRequest(authorization, body).execute();
    }

    /**
     * Create a new stablecoin wallet account.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter: Wallet account details
     * @return    Returns the CreateWalletResponse response from the API call
     */
    public CompletableFuture<CreateWalletResponse> createWalletAsync(
            final String authorization,
            final CreateWalletRequest body) {
        try {
            return prepareCreateWalletRequest(authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for createWallet.
     */
    private ApiCall<CreateWalletResponse, ApiException> prepareCreateWalletRequest(
            final String authorization,
            final CreateWalletRequest body) {
        return new ApiCall.Builder<CreateWalletResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/accounts/wallets")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, CreateWalletResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Retrieve a specific account (wallet or bank) by its unique identifier.
     * @param  id  Required parameter: Account ID (UUID)
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  includeSensitive  Optional parameter: If true, includes sensitive fields like
     *         bank_account_number.
     * @return    Returns the AccountResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public AccountResponse findOne2(
            final String id,
            final String authorization,
            final Boolean includeSensitive) throws ApiException, IOException {
        return prepareFindOne2Request(id, authorization, includeSensitive).execute();
    }

    /**
     * Retrieve a specific account (wallet or bank) by its unique identifier.
     * @param  id  Required parameter: Account ID (UUID)
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  includeSensitive  Optional parameter: If true, includes sensitive fields like
     *         bank_account_number.
     * @return    Returns the AccountResponse response from the API call
     */
    public CompletableFuture<AccountResponse> findOne2Async(
            final String id,
            final String authorization,
            final Boolean includeSensitive) {
        try {
            return prepareFindOne2Request(id, authorization, includeSensitive).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for findOne2.
     */
    private ApiCall<AccountResponse, ApiException> prepareFindOne2Request(
            final String id,
            final String authorization,
            final Boolean includeSensitive) {
        return new ApiCall.Builder<AccountResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/accounts/{id}")
                        .queryParam(param -> param.key("include_sensitive")
                                .value(includeSensitive).isRequired(false))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, AccountResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Update an existing account's information.
     * @param  id  Required parameter: Account ID (UUID)
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the UpdateAccountResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public UpdateAccountResponse update(
            final String id,
            final String authorization,
            final UpdateAccountRequest body) throws ApiException, IOException {
        return prepareUpdateRequest(id, authorization, body).execute();
    }

    /**
     * Update an existing account's information.
     * @param  id  Required parameter: Account ID (UUID)
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the UpdateAccountResponse response from the API call
     */
    public CompletableFuture<UpdateAccountResponse> updateAsync(
            final String id,
            final String authorization,
            final UpdateAccountRequest body) {
        try {
            return prepareUpdateRequest(id, authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for update.
     */
    private ApiCall<UpdateAccountResponse, ApiException> prepareUpdateRequest(
            final String id,
            final String authorization,
            final UpdateAccountRequest body) {
        return new ApiCall.Builder<UpdateAccountResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/accounts/{id}")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.PATCH))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, UpdateAccountResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}