/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.controllers;

import app.zuplo.tesserplatformv1pull51me98e48a7.ApiHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.Server;
import app.zuplo.tesserplatformv1pull51me98e48a7.exceptions.ApiException;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.request.HttpMethod;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.Currency;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class CurrenciesController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public CurrenciesController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Retrieve list of all supported currencies (crypto and fiat). Returns an array with currency
     * name, key, decimals, and network information.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @return    Returns the List of Currency response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public List<Currency> getCurrencies(
            final String authorization) throws ApiException, IOException {
        return prepareGetCurrenciesRequest(authorization).execute();
    }

    /**
     * Retrieve list of all supported currencies (crypto and fiat). Returns an array with currency
     * name, key, decimals, and network information.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @return    Returns the List of Currency response from the API call
     */
    public CompletableFuture<List<Currency>> getCurrenciesAsync(
            final String authorization) {
        try {
            return prepareGetCurrenciesRequest(authorization).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getCurrencies.
     */
    private ApiCall<List<Currency>, ApiException> prepareGetCurrenciesRequest(
            final String authorization) {
        return new ApiCall.Builder<List<Currency>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/currencies")
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        Currency[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}