/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.controllers;

import app.zuplo.tesserplatformv1pull51me98e48a7.ApiHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.Server;
import app.zuplo.tesserplatformv1pull51me98e48a7.exceptions.ApiException;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.request.HttpMethod;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.CreatePaymentRequest;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.PaymentListResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.PaymentResponse;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.PaymentType3Enum;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.ReviewPaymentRequest;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.UpdatePaymentRequest;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class PaymentsController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public PaymentsController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Retrieve all payments for the authenticated user's organization.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  startDate  Optional parameter: Filter payments created on or after this ISO 8601
     *         date.
     * @param  endDate  Optional parameter: Filter payments created before this ISO 8601 date.
     * @param  paymentType  Optional parameter: Filter payments by type ('withdrawal', 'deposit',
     *         'onramp', 'offramp', 'payment', 'transfer').
     * @param  page  Optional parameter: Page number for pagination (1-based).
     * @param  limit  Optional parameter: Number of items per page.
     * @return    Returns the PaymentListResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PaymentListResponse getPayments(
            final String authorization,
            final String startDate,
            final String endDate,
            final PaymentType3Enum paymentType,
            final Double page,
            final Double limit) throws ApiException, IOException {
        return prepareGetPaymentsRequest(authorization, startDate, endDate, paymentType, page,
                limit).execute();
    }

    /**
     * Retrieve all payments for the authenticated user's organization.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  startDate  Optional parameter: Filter payments created on or after this ISO 8601
     *         date.
     * @param  endDate  Optional parameter: Filter payments created before this ISO 8601 date.
     * @param  paymentType  Optional parameter: Filter payments by type ('withdrawal', 'deposit',
     *         'onramp', 'offramp', 'payment', 'transfer').
     * @param  page  Optional parameter: Page number for pagination (1-based).
     * @param  limit  Optional parameter: Number of items per page.
     * @return    Returns the PaymentListResponse response from the API call
     */
    public CompletableFuture<PaymentListResponse> getPaymentsAsync(
            final String authorization,
            final String startDate,
            final String endDate,
            final PaymentType3Enum paymentType,
            final Double page,
            final Double limit) {
        try {
            return prepareGetPaymentsRequest(authorization, startDate, endDate, paymentType, page,
            limit).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getPayments.
     */
    private ApiCall<PaymentListResponse, ApiException> prepareGetPaymentsRequest(
            final String authorization,
            final String startDate,
            final String endDate,
            final PaymentType3Enum paymentType,
            final Double page,
            final Double limit) {
        return new ApiCall.Builder<PaymentListResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payments")
                        .queryParam(param -> param.key("start_date")
                                .value(startDate).isRequired(false))
                        .queryParam(param -> param.key("end_date")
                                .value(endDate).isRequired(false))
                        .queryParam(param -> param.key("payment_type")
                                .value((paymentType != null) ? paymentType.value() : null).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value(page).isRequired(false))
                        .queryParam(param -> param.key("limit")
                                .value(limit).isRequired(false))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PaymentListResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Create a payment. Returns the created payment details.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PaymentResponse createPayment(
            final String authorization,
            final CreatePaymentRequest body) throws ApiException, IOException {
        return prepareCreatePaymentRequest(authorization, body).execute();
    }

    /**
     * Create a payment. Returns the created payment details.
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     */
    public CompletableFuture<PaymentResponse> createPaymentAsync(
            final String authorization,
            final CreatePaymentRequest body) {
        try {
            return prepareCreatePaymentRequest(authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for createPayment.
     */
    private ApiCall<PaymentResponse, ApiException> prepareCreatePaymentRequest(
            final String authorization,
            final CreatePaymentRequest body) {
        return new ApiCall.Builder<PaymentResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payments")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PaymentResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Retrieve a specific payment by ID.
     * @param  paymentId  Required parameter:
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @return    Returns the PaymentResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PaymentResponse getPaymentById(
            final String paymentId,
            final String authorization) throws ApiException, IOException {
        return prepareGetPaymentByIdRequest(paymentId, authorization).execute();
    }

    /**
     * Retrieve a specific payment by ID.
     * @param  paymentId  Required parameter:
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @return    Returns the PaymentResponse response from the API call
     */
    public CompletableFuture<PaymentResponse> getPaymentByIdAsync(
            final String paymentId,
            final String authorization) {
        try {
            return prepareGetPaymentByIdRequest(paymentId, authorization).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getPaymentById.
     */
    private ApiCall<PaymentResponse, ApiException> prepareGetPaymentByIdRequest(
            final String paymentId,
            final String authorization) {
        return new ApiCall.Builder<PaymentResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payments/{paymentId}")
                        .templateParam(param -> param.key("paymentId").value(paymentId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PaymentResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Update a payment with accounts.
     * @param  paymentId  Required parameter:
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PaymentResponse updatePayment(
            final String paymentId,
            final String authorization,
            final UpdatePaymentRequest body) throws ApiException, IOException {
        return prepareUpdatePaymentRequest(paymentId, authorization, body).execute();
    }

    /**
     * Update a payment with accounts.
     * @param  paymentId  Required parameter:
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     */
    public CompletableFuture<PaymentResponse> updatePaymentAsync(
            final String paymentId,
            final String authorization,
            final UpdatePaymentRequest body) {
        try {
            return prepareUpdatePaymentRequest(paymentId, authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for updatePayment.
     */
    private ApiCall<PaymentResponse, ApiException> prepareUpdatePaymentRequest(
            final String paymentId,
            final String authorization,
            final UpdatePaymentRequest body) {
        return new ApiCall.Builder<PaymentResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payments/{paymentId}")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("paymentId").value(paymentId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.PATCH))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PaymentResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Manually review and approve or reject a payment requiring risk review.
     * @param  paymentId  Required parameter: Unique identifier of the payment to review
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public PaymentResponse reviewPayment(
            final UUID paymentId,
            final String authorization,
            final ReviewPaymentRequest body) throws ApiException, IOException {
        return prepareReviewPaymentRequest(paymentId, authorization, body).execute();
    }

    /**
     * Manually review and approve or reject a payment requiring risk review.
     * @param  paymentId  Required parameter: Unique identifier of the payment to review
     * @param  authorization  Required parameter: Bearer token for authentication. To obtain a
     *         token, make a request to Auth0: ```bash curl --request POST \ --url
     *         https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \ --header 'content-type:
     *         application/json' \ --data '{ "client_id":"YOUR_CLIENT_ID",
     *         "client_secret":"YOUR_CLIENT_SECRET", "audience":"https://sandbox.tesserx.co",
     *         "grant_type":"client_credentials" }' ``` The response will contain an `access_token`
     *         field which should be used as the Bearer token.
     * @param  body  Required parameter:
     * @return    Returns the PaymentResponse response from the API call
     */
    public CompletableFuture<PaymentResponse> reviewPaymentAsync(
            final UUID paymentId,
            final String authorization,
            final ReviewPaymentRequest body) {
        try {
            return prepareReviewPaymentRequest(paymentId, authorization, body).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for reviewPayment.
     */
    private ApiCall<PaymentResponse, ApiException> prepareReviewPaymentRequest(
            final UUID paymentId,
            final String authorization,
            final ReviewPaymentRequest body) {
        return new ApiCall.Builder<PaymentResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payments/{paymentId}/review")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("paymentId").value(paymentId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("bearer"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, PaymentResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Details coming soon",
                                (reason, context) -> new ApiException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}