/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7;

import io.apimatic.core.utilities.CoreHelper;

/**
 * This is a Helper class with commonly used utilities for the SDK.
 */
public class ApiHelper extends CoreHelper {

}