/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7;

import io.apimatic.core.utilities.LocalDateTimeHelper;

/**
 * This is a utility class for DateTime operations.
 */
public class DateTimeHelper extends LocalDateTimeHelper {

}