/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7;

import app.zuplo.tesserplatformv1pull51me98e48a7.authentication.BearerAuthManager;
import app.zuplo.tesserplatformv1pull51me98e48a7.authentication.BearerAuthModel;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.AccountsController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.CounterpartiesController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.CurrenciesController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.ExperimentalController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.HealthController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.NetworksController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.PaymentsController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.TenantsController;
import app.zuplo.tesserplatformv1pull51me98e48a7.controllers.TreasuryController;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.client.HttpCallback;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.client.HttpClientConfiguration;
import app.zuplo.tesserplatformv1pull51me98e48a7.http.client.ReadonlyHttpClientConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class TesserAPIV1Client implements Configuration {

    /**
     * Private store for controllers.
     */
    private PaymentsController payments;
    private HealthController health;
    private AccountsController accounts;
    private CurrenciesController currencies;
    private CounterpartiesController counterparties;
    private TenantsController tenants;
    private NetworksController networks;
    private ExperimentalController experimental;
    private TreasuryController treasury;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * BearerAuthManager.
     */
    private BearerAuthManager bearerAuthManager;

    /**
     * The instance of BearerAuthModel.
     */
    private BearerAuthModel bearerAuthModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private TesserAPIV1Client(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, BearerAuthModel bearerAuthModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.bearerAuthModel = bearerAuthModel;

        this.bearerAuthManager = new BearerAuthManager(bearerAuthModel);
        this.authentications.put("bearer", bearerAuthManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        payments = new PaymentsController(globalConfig);
        health = new HealthController(globalConfig);
        accounts = new AccountsController(globalConfig);
        currencies = new CurrenciesController(globalConfig);
        counterparties = new CounterpartiesController(globalConfig);
        tenants = new TenantsController(globalConfig);
        networks = new NetworksController(globalConfig);
        experimental = new ExperimentalController(globalConfig);
        treasury = new TreasuryController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of PaymentsController.
     * @return payments
     */
    public PaymentsController getPaymentsController() {
        return payments;
    }

    /**
     * Get the instance of HealthController.
     * @return health
     */
    public HealthController getHealthController() {
        return health;
    }

    /**
     * Get the instance of AccountsController.
     * @return accounts
     */
    public AccountsController getAccountsController() {
        return accounts;
    }

    /**
     * Get the instance of CurrenciesController.
     * @return currencies
     */
    public CurrenciesController getCurrenciesController() {
        return currencies;
    }

    /**
     * Get the instance of CounterpartiesController.
     * @return counterparties
     */
    public CounterpartiesController getCounterpartiesController() {
        return counterparties;
    }

    /**
     * Get the instance of TenantsController.
     * @return tenants
     */
    public TenantsController getTenantsController() {
        return tenants;
    }

    /**
     * Get the instance of NetworksController.
     * @return networks
     */
    public NetworksController getNetworksController() {
        return networks;
    }

    /**
     * Get the instance of ExperimentalController.
     * @return experimental
     */
    public ExperimentalController getExperimentalController() {
        return experimental;
    }

    /**
     * Get the instance of TreasuryController.
     * @return treasury
     */
    public TreasuryController getTreasuryController() {
        return treasury;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with BearerAuth.
     * @return bearerAuthCredentials
     */
    public BearerAuthCredentials getBearerAuthCredentials() {
        return bearerAuthManager;
    }

    /**
     * The auth credential model for BearerAuth.
     * @return the instance of BearerAuthModel
     */
    public BearerAuthModel getBearerAuthModel() {
        return bearerAuthModel;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    public String getAccessToken() {
        return getBearerAuthCredentials().getAccessToken();
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        return environmentMapper(environment, server);
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://tesser-platform-v1-pull-51-me-98e48a7.zuplo.app";
            }
        }
        return "https://tesser-platform-v1-pull-51-me-98e48a7.zuplo.app";
    }

    /**
     * Converts this TesserAPIV1Client into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TesserAPIV1Client [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link TesserAPIV1Client.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link TesserAPIV1Client.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.bearerAuthCredentials(getBearerAuthModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link TesserAPIV1Client}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private BearerAuthModel bearerAuthModel = new BearerAuthModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for BearerAuth.
         * @param accessToken String value for accessToken.
         * @deprecated This builder method is deprecated.
         * Use {@link #bearerAuthCredentials(BearerAuthModel) bearerAuthCredentials} instead.
         * @return The current instance of builder.
         */
        @Deprecated
        public Builder accessToken(String accessToken) {
            bearerAuthModel = bearerAuthModel.toBuilder()
                .accessToken(accessToken)
                .build();
            return this;
        }

        /**
         * Credentials setter for BearerAuthCredentials.
         * @param bearerAuthModel The instance of BearerAuthModel.
         * @return The current instance of builder.
         */
        public Builder bearerAuthCredentials(BearerAuthModel bearerAuthModel) {
            this.bearerAuthModel = bearerAuthModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new TesserAPIV1Client object using the set fields.
         * @return TesserAPIV1Client
         */
        public TesserAPIV1Client build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new TesserAPIV1Client(environment, httpClient, httpClientConfig, bearerAuthModel,
                    httpCallback);
        }
    }
}