/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.http.request;

import io.apimatic.coreinterfaces.http.Method;

/**
 * HTTP methods enumeration.
 */
public enum HttpMethod implements Method {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE,
    HEAD
}
