/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models.containers;

import app.zuplo.tesserplatformv1pull51me98e48a7.ApiHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.ProviderKeyEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = TransferStepProviderKey.TransferStepProviderKeyDeserializer.class)
public abstract class TransferStepProviderKey {
    
    /**
     * This is ProviderKey case.
     * @param providerKey ProviderKeyEnum value for providerKey.
     * @return The ProviderKeyCase object.
     */
    public static TransferStepProviderKey fromProviderKey(ProviderKeyEnum providerKey) {
        return providerKey == null ? null : new ProviderKeyCase(providerKey);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R providerKey(ProviderKeyEnum providerKey);
    }

    /**
     * This is a implementation class for ProviderKeyCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ProviderKeyEnum")
    private static class ProviderKeyCase extends TransferStepProviderKey {

        @JsonValue
        private ProviderKeyEnum providerKey;

        ProviderKeyCase(ProviderKeyEnum providerKey) {
            this.providerKey = providerKey;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.providerKey(this.providerKey);
        }

        @JsonCreator
        private ProviderKeyCase(JsonNode jsonNode) throws IOException {
            this.providerKey = 
                ProviderKeyEnum.fromString(ApiHelper.deserialize(jsonNode, String.class));
            if (this.providerKey == null) {
                throw new IllegalArgumentException();
            }
        }

        @Override
        public String toString() {
            return providerKey.toString();
        }
    }

    /**
     * This is a custom deserializer class for TransferStepProviderKey.
     */
    protected static class TransferStepProviderKeyDeserializer
            extends JsonDeserializer<TransferStepProviderKey> {

        @Override
        public TransferStepProviderKey deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(ProviderKeyCase.class), false);
        }
    }

}
