/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models.containers;

import app.zuplo.tesserplatformv1pull51me98e48a7.ApiHelper;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = UpdateCounterpartyRequestTenantId.UpdateCounterpartyRequestTenantIdDeserializer.class)
public abstract class UpdateCounterpartyRequestTenantId {
    
    /**
     * This is UUID case.
     * @param uUID UUID value for uUID.
     * @return The UUIDCase object.
     */
    public static UpdateCounterpartyRequestTenantId fromUUID(UUID uUID) {
        return uUID == null ? null : new UUIDCase(uUID);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R uUID(UUID uUID);
    }

    /**
     * This is a implementation class for UUIDCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "UUID")
    private static class UUIDCase extends UpdateCounterpartyRequestTenantId {

        @JsonValue
        private UUID uUID;

        UUIDCase(UUID uUID) {
            this.uUID = uUID;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.uUID(this.uUID);
        }

        @JsonCreator
        private UUIDCase(JsonNode jsonNode) throws IOException {
            this.uUID = UUID.fromString(jsonNode.asText());
        }

        @Override
        public String toString() {
            return uUID.toString();
        }
    }

    /**
     * This is a custom deserializer class for UpdateCounterpartyRequestTenantId.
     */
    protected static class UpdateCounterpartyRequestTenantIdDeserializer
            extends JsonDeserializer<UpdateCounterpartyRequestTenantId> {

        @Override
        public UpdateCounterpartyRequestTenantId deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(UUIDCase.class), false);
        }
    }

}
