/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeBankCodeType;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeBankIdentifierCode;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeBankName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeCounterpartyId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeCryptoWalletAddress;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountSafeTenantId;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountSafe type.
 */
public class AccountSafe {
    private String id;
    private String workspaceId;
    private AccountSafeTenantId tenantId;
    private AccountSafeCounterpartyId counterpartyId;
    private TypeEnum type;
    private String name;
    private AccountSafeBankName bankName;
    private AccountSafeBankCodeType bankCodeType;
    private AccountSafeBankIdentifierCode bankIdentifierCode;
    private AccountSafeCryptoWalletAddress cryptoWalletAddress;
    private String createdAt;
    private String updatedAt;

    /**
     * Default constructor.
     */
    public AccountSafe() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  type  TypeEnum value for type.
     * @param  name  String value for name.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     * @param  workspaceId  String value for workspaceId.
     * @param  tenantId  AccountSafeTenantId value for tenantId.
     * @param  counterpartyId  AccountSafeCounterpartyId value for counterpartyId.
     * @param  bankName  AccountSafeBankName value for bankName.
     * @param  bankCodeType  AccountSafeBankCodeType value for bankCodeType.
     * @param  bankIdentifierCode  AccountSafeBankIdentifierCode value for bankIdentifierCode.
     * @param  cryptoWalletAddress  AccountSafeCryptoWalletAddress value for cryptoWalletAddress.
     */
    public AccountSafe(
            String id,
            TypeEnum type,
            String name,
            String createdAt,
            String updatedAt,
            String workspaceId,
            AccountSafeTenantId tenantId,
            AccountSafeCounterpartyId counterpartyId,
            AccountSafeBankName bankName,
            AccountSafeBankCodeType bankCodeType,
            AccountSafeBankIdentifierCode bankIdentifierCode,
            AccountSafeCryptoWalletAddress cryptoWalletAddress) {
        this.id = id;
        this.workspaceId = workspaceId;
        this.tenantId = tenantId;
        this.counterpartyId = counterpartyId;
        this.type = type;
        this.name = name;
        this.bankName = bankName;
        this.bankCodeType = bankCodeType;
        this.bankIdentifierCode = bankIdentifierCode;
        this.cryptoWalletAddress = cryptoWalletAddress;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for Id.
     * Unique identifier for the account.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for the account.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for WorkspaceId.
     * ID of the workspace.
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * ID of the workspace.
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for TenantId.
     * Tenant ID (optional - if provided, this account is associated with a tenant). At most one of
     * tenant_id or counterparty_id may be set.
     * @return Returns the AccountSafeTenantId
     */
    @JsonGetter("tenant_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeTenantId getTenantId() {
        return tenantId;
    }

    /**
     * Setter for TenantId.
     * Tenant ID (optional - if provided, this account is associated with a tenant). At most one of
     * tenant_id or counterparty_id may be set.
     * @param tenantId Value for AccountSafeTenantId
     */
    @JsonSetter("tenant_id")
    public void setTenantId(AccountSafeTenantId tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for CounterpartyId.
     * Counterparty ID (optional - if provided, this account is associated with a counterparty). At
     * most one of tenant_id or counterparty_id may be set.
     * @return Returns the AccountSafeCounterpartyId
     */
    @JsonGetter("counterparty_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeCounterpartyId getCounterpartyId() {
        return counterpartyId;
    }

    /**
     * Setter for CounterpartyId.
     * Counterparty ID (optional - if provided, this account is associated with a counterparty). At
     * most one of tenant_id or counterparty_id may be set.
     * @param counterpartyId Value for AccountSafeCounterpartyId
     */
    @JsonSetter("counterparty_id")
    public void setCounterpartyId(AccountSafeCounterpartyId counterpartyId) {
        this.counterpartyId = counterpartyId;
    }

    /**
     * Getter for Type.
     * Account type.
     * @return Returns the TypeEnum
     */
    @JsonGetter("type")
    public TypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Account type.
     * @param type Value for TypeEnum
     */
    @JsonSetter("type")
    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * Getter for Name.
     * Account name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Account name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for BankName.
     * Bank name (for fiat accounts).
     * @return Returns the AccountSafeBankName
     */
    @JsonGetter("bank_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeBankName getBankName() {
        return bankName;
    }

    /**
     * Setter for BankName.
     * Bank name (for fiat accounts).
     * @param bankName Value for AccountSafeBankName
     */
    @JsonSetter("bank_name")
    public void setBankName(AccountSafeBankName bankName) {
        this.bankName = bankName;
    }

    /**
     * Getter for BankCodeType.
     * Bank code type (e.g., SWIFT, BIC).
     * @return Returns the AccountSafeBankCodeType
     */
    @JsonGetter("bank_code_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeBankCodeType getBankCodeType() {
        return bankCodeType;
    }

    /**
     * Setter for BankCodeType.
     * Bank code type (e.g., SWIFT, BIC).
     * @param bankCodeType Value for AccountSafeBankCodeType
     */
    @JsonSetter("bank_code_type")
    public void setBankCodeType(AccountSafeBankCodeType bankCodeType) {
        this.bankCodeType = bankCodeType;
    }

    /**
     * Getter for BankIdentifierCode.
     * Bank identifier code value.
     * @return Returns the AccountSafeBankIdentifierCode
     */
    @JsonGetter("bank_identifier_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeBankIdentifierCode getBankIdentifierCode() {
        return bankIdentifierCode;
    }

    /**
     * Setter for BankIdentifierCode.
     * Bank identifier code value.
     * @param bankIdentifierCode Value for AccountSafeBankIdentifierCode
     */
    @JsonSetter("bank_identifier_code")
    public void setBankIdentifierCode(AccountSafeBankIdentifierCode bankIdentifierCode) {
        this.bankIdentifierCode = bankIdentifierCode;
    }

    /**
     * Getter for CryptoWalletAddress.
     * Crypto wallet address (for wallet accounts).
     * @return Returns the AccountSafeCryptoWalletAddress
     */
    @JsonGetter("crypto_wallet_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountSafeCryptoWalletAddress getCryptoWalletAddress() {
        return cryptoWalletAddress;
    }

    /**
     * Setter for CryptoWalletAddress.
     * Crypto wallet address (for wallet accounts).
     * @param cryptoWalletAddress Value for AccountSafeCryptoWalletAddress
     */
    @JsonSetter("crypto_wallet_address")
    public void setCryptoWalletAddress(AccountSafeCryptoWalletAddress cryptoWalletAddress) {
        this.cryptoWalletAddress = cryptoWalletAddress;
    }

    /**
     * Getter for CreatedAt.
     * Creation timestamp.
     * @return Returns the String
     */
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Creation timestamp.
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * Last update timestamp.
     * @return Returns the String
     */
    @JsonGetter("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * Last update timestamp.
     * @param updatedAt Value for String
     */
    @JsonSetter("updated_at")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Converts this AccountSafe into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountSafe [" + "id=" + id + ", type=" + type + ", name=" + name + ", createdAt="
                + createdAt + ", updatedAt=" + updatedAt + ", workspaceId=" + workspaceId
                + ", tenantId=" + tenantId + ", counterpartyId=" + counterpartyId + ", bankName="
                + bankName + ", bankCodeType=" + bankCodeType + ", bankIdentifierCode="
                + bankIdentifierCode + ", cryptoWalletAddress=" + cryptoWalletAddress + "]";
    }

    /**
     * Builds a new {@link AccountSafe.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountSafe.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, type, name, createdAt, updatedAt)
                .workspaceId(getWorkspaceId())
                .tenantId(getTenantId())
                .counterpartyId(getCounterpartyId())
                .bankName(getBankName())
                .bankCodeType(getBankCodeType())
                .bankIdentifierCode(getBankIdentifierCode())
                .cryptoWalletAddress(getCryptoWalletAddress());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountSafe}.
     */
    public static class Builder {
        private String id;
        private TypeEnum type;
        private String name;
        private String createdAt;
        private String updatedAt;
        private String workspaceId;
        private AccountSafeTenantId tenantId;
        private AccountSafeCounterpartyId counterpartyId;
        private AccountSafeBankName bankName;
        private AccountSafeBankCodeType bankCodeType;
        private AccountSafeBankIdentifierCode bankIdentifierCode;
        private AccountSafeCryptoWalletAddress cryptoWalletAddress;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  type  TypeEnum value for type.
         * @param  name  String value for name.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         */
        public Builder(String id, TypeEnum type, String name, String createdAt, String updatedAt) {
            this.id = id;
            this.type = type;
            this.name = name;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  TypeEnum value for type.
         * @return Builder
         */
        public Builder type(TypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for tenantId.
         * @param  tenantId  AccountSafeTenantId value for tenantId.
         * @return Builder
         */
        public Builder tenantId(AccountSafeTenantId tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        /**
         * Setter for counterpartyId.
         * @param  counterpartyId  AccountSafeCounterpartyId value for counterpartyId.
         * @return Builder
         */
        public Builder counterpartyId(AccountSafeCounterpartyId counterpartyId) {
            this.counterpartyId = counterpartyId;
            return this;
        }

        /**
         * Setter for bankName.
         * @param  bankName  AccountSafeBankName value for bankName.
         * @return Builder
         */
        public Builder bankName(AccountSafeBankName bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Setter for bankCodeType.
         * @param  bankCodeType  AccountSafeBankCodeType value for bankCodeType.
         * @return Builder
         */
        public Builder bankCodeType(AccountSafeBankCodeType bankCodeType) {
            this.bankCodeType = bankCodeType;
            return this;
        }

        /**
         * Setter for bankIdentifierCode.
         * @param  bankIdentifierCode  AccountSafeBankIdentifierCode value for bankIdentifierCode.
         * @return Builder
         */
        public Builder bankIdentifierCode(AccountSafeBankIdentifierCode bankIdentifierCode) {
            this.bankIdentifierCode = bankIdentifierCode;
            return this;
        }

        /**
         * Setter for cryptoWalletAddress.
         * @param  cryptoWalletAddress  AccountSafeCryptoWalletAddress value for
         *         cryptoWalletAddress.
         * @return Builder
         */
        public Builder cryptoWalletAddress(AccountSafeCryptoWalletAddress cryptoWalletAddress) {
            this.cryptoWalletAddress = cryptoWalletAddress;
            return this;
        }

        /**
         * Builds a new {@link AccountSafe} object using the set fields.
         * @return {@link AccountSafe}
         */
        public AccountSafe build() {
            return new AccountSafe(id, type, name, createdAt, updatedAt, workspaceId, tenantId,
                    counterpartyId, bankName, bankCodeType, bankIdentifierCode,
                    cryptoWalletAddress);
        }
    }
}
