/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountResponse type.
 */
public class AccountResponse {
    private Account data;

    /**
     * Default constructor.
     */
    public AccountResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Account value for data.
     */
    public AccountResponse(
            Account data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Account
     */
    @JsonGetter("data")
    public Account getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Account
     */
    @JsonSetter("data")
    public void setData(Account data) {
        this.data = data;
    }

    /**
     * Converts this AccountResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link AccountResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link AccountResponse}.
     */
    public static class Builder {
        private Account data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Account value for data.
         */
        public Builder(Account data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Account value for data.
         * @return Builder
         */
        public Builder data(Account data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link AccountResponse} object using the set fields.
         * @return {@link AccountResponse}
         */
        public AccountResponse build() {
            return new AccountResponse(data);
        }
    }
}
