/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemBankAccountNumber;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemBankCodeType;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemBankIdentifierCode;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemBankName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemCounterpartyId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemCryptoWalletAddress;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.AccountListItemTenantId;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountListItem type.
 */
public class AccountListItem {
    private String id;
    private String workspaceId;
    private AccountListItemTenantId tenantId;
    private AccountListItemCounterpartyId counterpartyId;
    private TypeEnum type;
    private String name;
    private AccountListItemBankName bankName;
    private AccountListItemBankCodeType bankCodeType;
    private AccountListItemBankIdentifierCode bankIdentifierCode;
    private AccountListItemCryptoWalletAddress cryptoWalletAddress;
    private AccountListItemBankAccountNumber bankAccountNumber;
    private String createdAt;
    private String updatedAt;

    /**
     * Default constructor.
     */
    public AccountListItem() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  type  TypeEnum value for type.
     * @param  name  String value for name.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     * @param  workspaceId  String value for workspaceId.
     * @param  tenantId  AccountListItemTenantId value for tenantId.
     * @param  counterpartyId  AccountListItemCounterpartyId value for counterpartyId.
     * @param  bankName  AccountListItemBankName value for bankName.
     * @param  bankCodeType  AccountListItemBankCodeType value for bankCodeType.
     * @param  bankIdentifierCode  AccountListItemBankIdentifierCode value for bankIdentifierCode.
     * @param  cryptoWalletAddress  AccountListItemCryptoWalletAddress value for
     *         cryptoWalletAddress.
     * @param  bankAccountNumber  AccountListItemBankAccountNumber value for bankAccountNumber.
     */
    public AccountListItem(
            String id,
            TypeEnum type,
            String name,
            String createdAt,
            String updatedAt,
            String workspaceId,
            AccountListItemTenantId tenantId,
            AccountListItemCounterpartyId counterpartyId,
            AccountListItemBankName bankName,
            AccountListItemBankCodeType bankCodeType,
            AccountListItemBankIdentifierCode bankIdentifierCode,
            AccountListItemCryptoWalletAddress cryptoWalletAddress,
            AccountListItemBankAccountNumber bankAccountNumber) {
        this.id = id;
        this.workspaceId = workspaceId;
        this.tenantId = tenantId;
        this.counterpartyId = counterpartyId;
        this.type = type;
        this.name = name;
        this.bankName = bankName;
        this.bankCodeType = bankCodeType;
        this.bankIdentifierCode = bankIdentifierCode;
        this.cryptoWalletAddress = cryptoWalletAddress;
        this.bankAccountNumber = bankAccountNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for Id.
     * Unique identifier for the account.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for the account.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for WorkspaceId.
     * ID of the workspace.
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * ID of the workspace.
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for TenantId.
     * Tenant ID (optional - if provided, this account is associated with a tenant). At most one of
     * tenant_id or counterparty_id may be set.
     * @return Returns the AccountListItemTenantId
     */
    @JsonGetter("tenant_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemTenantId getTenantId() {
        return tenantId;
    }

    /**
     * Setter for TenantId.
     * Tenant ID (optional - if provided, this account is associated with a tenant). At most one of
     * tenant_id or counterparty_id may be set.
     * @param tenantId Value for AccountListItemTenantId
     */
    @JsonSetter("tenant_id")
    public void setTenantId(AccountListItemTenantId tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for CounterpartyId.
     * Counterparty ID (optional - if provided, this account is associated with a counterparty). At
     * most one of tenant_id or counterparty_id may be set.
     * @return Returns the AccountListItemCounterpartyId
     */
    @JsonGetter("counterparty_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemCounterpartyId getCounterpartyId() {
        return counterpartyId;
    }

    /**
     * Setter for CounterpartyId.
     * Counterparty ID (optional - if provided, this account is associated with a counterparty). At
     * most one of tenant_id or counterparty_id may be set.
     * @param counterpartyId Value for AccountListItemCounterpartyId
     */
    @JsonSetter("counterparty_id")
    public void setCounterpartyId(AccountListItemCounterpartyId counterpartyId) {
        this.counterpartyId = counterpartyId;
    }

    /**
     * Getter for Type.
     * Account type.
     * @return Returns the TypeEnum
     */
    @JsonGetter("type")
    public TypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Account type.
     * @param type Value for TypeEnum
     */
    @JsonSetter("type")
    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * Getter for Name.
     * Account name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Account name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for BankName.
     * Bank name (for fiat accounts).
     * @return Returns the AccountListItemBankName
     */
    @JsonGetter("bank_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemBankName getBankName() {
        return bankName;
    }

    /**
     * Setter for BankName.
     * Bank name (for fiat accounts).
     * @param bankName Value for AccountListItemBankName
     */
    @JsonSetter("bank_name")
    public void setBankName(AccountListItemBankName bankName) {
        this.bankName = bankName;
    }

    /**
     * Getter for BankCodeType.
     * Bank code type (e.g., SWIFT, BIC).
     * @return Returns the AccountListItemBankCodeType
     */
    @JsonGetter("bank_code_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemBankCodeType getBankCodeType() {
        return bankCodeType;
    }

    /**
     * Setter for BankCodeType.
     * Bank code type (e.g., SWIFT, BIC).
     * @param bankCodeType Value for AccountListItemBankCodeType
     */
    @JsonSetter("bank_code_type")
    public void setBankCodeType(AccountListItemBankCodeType bankCodeType) {
        this.bankCodeType = bankCodeType;
    }

    /**
     * Getter for BankIdentifierCode.
     * Bank identifier code value.
     * @return Returns the AccountListItemBankIdentifierCode
     */
    @JsonGetter("bank_identifier_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemBankIdentifierCode getBankIdentifierCode() {
        return bankIdentifierCode;
    }

    /**
     * Setter for BankIdentifierCode.
     * Bank identifier code value.
     * @param bankIdentifierCode Value for AccountListItemBankIdentifierCode
     */
    @JsonSetter("bank_identifier_code")
    public void setBankIdentifierCode(AccountListItemBankIdentifierCode bankIdentifierCode) {
        this.bankIdentifierCode = bankIdentifierCode;
    }

    /**
     * Getter for CryptoWalletAddress.
     * Crypto wallet address (for wallet accounts).
     * @return Returns the AccountListItemCryptoWalletAddress
     */
    @JsonGetter("crypto_wallet_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemCryptoWalletAddress getCryptoWalletAddress() {
        return cryptoWalletAddress;
    }

    /**
     * Setter for CryptoWalletAddress.
     * Crypto wallet address (for wallet accounts).
     * @param cryptoWalletAddress Value for AccountListItemCryptoWalletAddress
     */
    @JsonSetter("crypto_wallet_address")
    public void setCryptoWalletAddress(AccountListItemCryptoWalletAddress cryptoWalletAddress) {
        this.cryptoWalletAddress = cryptoWalletAddress;
    }

    /**
     * Getter for BankAccountNumber.
     * Bank account number (IBAN, etc). Only returned if include_sensitive=true.
     * @return Returns the AccountListItemBankAccountNumber
     */
    @JsonGetter("bank_account_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountListItemBankAccountNumber getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * Setter for BankAccountNumber.
     * Bank account number (IBAN, etc). Only returned if include_sensitive=true.
     * @param bankAccountNumber Value for AccountListItemBankAccountNumber
     */
    @JsonSetter("bank_account_number")
    public void setBankAccountNumber(AccountListItemBankAccountNumber bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    /**
     * Getter for CreatedAt.
     * Creation timestamp.
     * @return Returns the String
     */
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Creation timestamp.
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * Last update timestamp.
     * @return Returns the String
     */
    @JsonGetter("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * Last update timestamp.
     * @param updatedAt Value for String
     */
    @JsonSetter("updated_at")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Converts this AccountListItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountListItem [" + "id=" + id + ", type=" + type + ", name=" + name
                + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + ", workspaceId="
                + workspaceId + ", tenantId=" + tenantId + ", counterpartyId=" + counterpartyId
                + ", bankName=" + bankName + ", bankCodeType=" + bankCodeType
                + ", bankIdentifierCode=" + bankIdentifierCode + ", cryptoWalletAddress="
                + cryptoWalletAddress + ", bankAccountNumber=" + bankAccountNumber + "]";
    }

    /**
     * Builds a new {@link AccountListItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountListItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, type, name, createdAt, updatedAt)
                .workspaceId(getWorkspaceId())
                .tenantId(getTenantId())
                .counterpartyId(getCounterpartyId())
                .bankName(getBankName())
                .bankCodeType(getBankCodeType())
                .bankIdentifierCode(getBankIdentifierCode())
                .cryptoWalletAddress(getCryptoWalletAddress())
                .bankAccountNumber(getBankAccountNumber());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountListItem}.
     */
    public static class Builder {
        private String id;
        private TypeEnum type;
        private String name;
        private String createdAt;
        private String updatedAt;
        private String workspaceId;
        private AccountListItemTenantId tenantId;
        private AccountListItemCounterpartyId counterpartyId;
        private AccountListItemBankName bankName;
        private AccountListItemBankCodeType bankCodeType;
        private AccountListItemBankIdentifierCode bankIdentifierCode;
        private AccountListItemCryptoWalletAddress cryptoWalletAddress;
        private AccountListItemBankAccountNumber bankAccountNumber;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  type  TypeEnum value for type.
         * @param  name  String value for name.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         */
        public Builder(String id, TypeEnum type, String name, String createdAt, String updatedAt) {
            this.id = id;
            this.type = type;
            this.name = name;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  TypeEnum value for type.
         * @return Builder
         */
        public Builder type(TypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for tenantId.
         * @param  tenantId  AccountListItemTenantId value for tenantId.
         * @return Builder
         */
        public Builder tenantId(AccountListItemTenantId tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        /**
         * Setter for counterpartyId.
         * @param  counterpartyId  AccountListItemCounterpartyId value for counterpartyId.
         * @return Builder
         */
        public Builder counterpartyId(AccountListItemCounterpartyId counterpartyId) {
            this.counterpartyId = counterpartyId;
            return this;
        }

        /**
         * Setter for bankName.
         * @param  bankName  AccountListItemBankName value for bankName.
         * @return Builder
         */
        public Builder bankName(AccountListItemBankName bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Setter for bankCodeType.
         * @param  bankCodeType  AccountListItemBankCodeType value for bankCodeType.
         * @return Builder
         */
        public Builder bankCodeType(AccountListItemBankCodeType bankCodeType) {
            this.bankCodeType = bankCodeType;
            return this;
        }

        /**
         * Setter for bankIdentifierCode.
         * @param  bankIdentifierCode  AccountListItemBankIdentifierCode value for
         *         bankIdentifierCode.
         * @return Builder
         */
        public Builder bankIdentifierCode(AccountListItemBankIdentifierCode bankIdentifierCode) {
            this.bankIdentifierCode = bankIdentifierCode;
            return this;
        }

        /**
         * Setter for cryptoWalletAddress.
         * @param  cryptoWalletAddress  AccountListItemCryptoWalletAddress value for
         *         cryptoWalletAddress.
         * @return Builder
         */
        public Builder cryptoWalletAddress(
                AccountListItemCryptoWalletAddress cryptoWalletAddress) {
            this.cryptoWalletAddress = cryptoWalletAddress;
            return this;
        }

        /**
         * Setter for bankAccountNumber.
         * @param  bankAccountNumber  AccountListItemBankAccountNumber value for bankAccountNumber.
         * @return Builder
         */
        public Builder bankAccountNumber(AccountListItemBankAccountNumber bankAccountNumber) {
            this.bankAccountNumber = bankAccountNumber;
            return this;
        }

        /**
         * Builds a new {@link AccountListItem} object using the set fields.
         * @return {@link AccountListItem}
         */
        public AccountListItem build() {
            return new AccountListItem(id, type, name, createdAt, updatedAt, workspaceId, tenantId,
                    counterpartyId, bankName, bankCodeType, bankIdentifierCode, cryptoWalletAddress,
                    bankAccountNumber);
        }
    }
}
