/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CounterpartyListResponse type.
 */
public class CounterpartyListResponse {
    private List<Counterparty> data;

    /**
     * Default constructor.
     */
    public CounterpartyListResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Counterparty value for data.
     */
    public CounterpartyListResponse(
            List<Counterparty> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * List of counterparties
     * @return Returns the List of Counterparty
     */
    @JsonGetter("data")
    public List<Counterparty> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * List of counterparties
     * @param data Value for List of Counterparty
     */
    @JsonSetter("data")
    public void setData(List<Counterparty> data) {
        this.data = data;
    }

    /**
     * Converts this CounterpartyListResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CounterpartyListResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link CounterpartyListResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CounterpartyListResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link CounterpartyListResponse}.
     */
    public static class Builder {
        private List<Counterparty> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Counterparty value for data.
         */
        public Builder(List<Counterparty> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of Counterparty value for data.
         * @return Builder
         */
        public Builder data(List<Counterparty> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link CounterpartyListResponse} object using the set fields.
         * @return {@link CounterpartyListResponse}
         */
        public CounterpartyListResponse build() {
            return new CounterpartyListResponse(data);
        }
    }
}
