/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateDepositRequest type.
 */
public class CreateDepositRequest {
    private String fromCurrency;
    private String toCurrency;
    private String fromAmount;
    private String toAmount;
    private String tenantId;
    private String toAccountId;
    private String toNetwork;

    /**
     * Default constructor.
     */
    public CreateDepositRequest() {
    }

    /**
     * Initialization constructor.
     * @param  fromCurrency  String value for fromCurrency.
     * @param  toCurrency  String value for toCurrency.
     * @param  toAccountId  String value for toAccountId.
     * @param  toNetwork  String value for toNetwork.
     * @param  fromAmount  String value for fromAmount.
     * @param  toAmount  String value for toAmount.
     * @param  tenantId  String value for tenantId.
     */
    public CreateDepositRequest(
            String fromCurrency,
            String toCurrency,
            String toAccountId,
            String toNetwork,
            String fromAmount,
            String toAmount,
            String tenantId) {
        this.fromCurrency = fromCurrency;
        this.toCurrency = toCurrency;
        this.fromAmount = fromAmount;
        this.toAmount = toAmount;
        this.tenantId = tenantId;
        this.toAccountId = toAccountId;
        this.toNetwork = toNetwork;
    }

    /**
     * Getter for FromCurrency.
     * Source currency code.
     * @return Returns the String
     */
    @JsonGetter("from_currency")
    public String getFromCurrency() {
        return fromCurrency;
    }

    /**
     * Setter for FromCurrency.
     * Source currency code.
     * @param fromCurrency Value for String
     */
    @JsonSetter("from_currency")
    public void setFromCurrency(String fromCurrency) {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Getter for ToCurrency.
     * Destination currency code.
     * @return Returns the String
     */
    @JsonGetter("to_currency")
    public String getToCurrency() {
        return toCurrency;
    }

    /**
     * Setter for ToCurrency.
     * Destination currency code.
     * @param toCurrency Value for String
     */
    @JsonSetter("to_currency")
    public void setToCurrency(String toCurrency) {
        this.toCurrency = toCurrency;
    }

    /**
     * Getter for FromAmount.
     * Amount to send. Required if to_amount is missing.
     * @return Returns the String
     */
    @JsonGetter("from_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFromAmount() {
        return fromAmount;
    }

    /**
     * Setter for FromAmount.
     * Amount to send. Required if to_amount is missing.
     * @param fromAmount Value for String
     */
    @JsonSetter("from_amount")
    public void setFromAmount(String fromAmount) {
        this.fromAmount = fromAmount;
    }

    /**
     * Getter for ToAmount.
     * Amount to receive. Required if from_amount is missing.
     * @return Returns the String
     */
    @JsonGetter("to_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToAmount() {
        return toAmount;
    }

    /**
     * Setter for ToAmount.
     * Amount to receive. Required if from_amount is missing.
     * @param toAmount Value for String
     */
    @JsonSetter("to_amount")
    public void setToAmount(String toAmount) {
        this.toAmount = toAmount;
    }

    /**
     * Getter for TenantId.
     * Optional tenant ID.
     * @return Returns the String
     */
    @JsonGetter("tenant_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Setter for TenantId.
     * Optional tenant ID.
     * @param tenantId Value for String
     */
    @JsonSetter("tenant_id")
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for ToAccountId.
     * Destination account ID.
     * @return Returns the String
     */
    @JsonGetter("to_account_id")
    public String getToAccountId() {
        return toAccountId;
    }

    /**
     * Setter for ToAccountId.
     * Destination account ID.
     * @param toAccountId Value for String
     */
    @JsonSetter("to_account_id")
    public void setToAccountId(String toAccountId) {
        this.toAccountId = toAccountId;
    }

    /**
     * Getter for ToNetwork.
     * Network for the deposit.
     * @return Returns the String
     */
    @JsonGetter("to_network")
    public String getToNetwork() {
        return toNetwork;
    }

    /**
     * Setter for ToNetwork.
     * Network for the deposit.
     * @param toNetwork Value for String
     */
    @JsonSetter("to_network")
    public void setToNetwork(String toNetwork) {
        this.toNetwork = toNetwork;
    }

    /**
     * Converts this CreateDepositRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateDepositRequest [" + "fromCurrency=" + fromCurrency + ", toCurrency="
                + toCurrency + ", toAccountId=" + toAccountId + ", toNetwork=" + toNetwork
                + ", fromAmount=" + fromAmount + ", toAmount=" + toAmount + ", tenantId=" + tenantId
                + "]";
    }

    /**
     * Builds a new {@link CreateDepositRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateDepositRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(fromCurrency, toCurrency, toAccountId, toNetwork)
                .fromAmount(getFromAmount())
                .toAmount(getToAmount())
                .tenantId(getTenantId());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateDepositRequest}.
     */
    public static class Builder {
        private String fromCurrency;
        private String toCurrency;
        private String toAccountId;
        private String toNetwork;
        private String fromAmount;
        private String toAmount;
        private String tenantId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  fromCurrency  String value for fromCurrency.
         * @param  toCurrency  String value for toCurrency.
         * @param  toAccountId  String value for toAccountId.
         * @param  toNetwork  String value for toNetwork.
         */
        public Builder(String fromCurrency, String toCurrency, String toAccountId,
                String toNetwork) {
            this.fromCurrency = fromCurrency;
            this.toCurrency = toCurrency;
            this.toAccountId = toAccountId;
            this.toNetwork = toNetwork;
        }

        /**
         * Setter for fromCurrency.
         * @param  fromCurrency  String value for fromCurrency.
         * @return Builder
         */
        public Builder fromCurrency(String fromCurrency) {
            this.fromCurrency = fromCurrency;
            return this;
        }

        /**
         * Setter for toCurrency.
         * @param  toCurrency  String value for toCurrency.
         * @return Builder
         */
        public Builder toCurrency(String toCurrency) {
            this.toCurrency = toCurrency;
            return this;
        }

        /**
         * Setter for toAccountId.
         * @param  toAccountId  String value for toAccountId.
         * @return Builder
         */
        public Builder toAccountId(String toAccountId) {
            this.toAccountId = toAccountId;
            return this;
        }

        /**
         * Setter for toNetwork.
         * @param  toNetwork  String value for toNetwork.
         * @return Builder
         */
        public Builder toNetwork(String toNetwork) {
            this.toNetwork = toNetwork;
            return this;
        }

        /**
         * Setter for fromAmount.
         * @param  fromAmount  String value for fromAmount.
         * @return Builder
         */
        public Builder fromAmount(String fromAmount) {
            this.fromAmount = fromAmount;
            return this;
        }

        /**
         * Setter for toAmount.
         * @param  toAmount  String value for toAmount.
         * @return Builder
         */
        public Builder toAmount(String toAmount) {
            this.toAmount = toAmount;
            return this;
        }

        /**
         * Setter for tenantId.
         * @param  tenantId  String value for tenantId.
         * @return Builder
         */
        public Builder tenantId(String tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        /**
         * Builds a new {@link CreateDepositRequest} object using the set fields.
         * @return {@link CreateDepositRequest}
         */
        public CreateDepositRequest build() {
            return new CreateDepositRequest(fromCurrency, toCurrency, toAccountId, toNetwork,
                    fromAmount, toAmount, tenantId);
        }
    }
}
