/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateWalletResponse type.
 */
public class CreateWalletResponse {
    private AccountSafe data;

    /**
     * Default constructor.
     */
    public CreateWalletResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  AccountSafe value for data.
     */
    public CreateWalletResponse(
            AccountSafe data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the AccountSafe
     */
    @JsonGetter("data")
    public AccountSafe getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for AccountSafe
     */
    @JsonSetter("data")
    public void setData(AccountSafe data) {
        this.data = data;
    }

    /**
     * Converts this CreateWalletResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateWalletResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link CreateWalletResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateWalletResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link CreateWalletResponse}.
     */
    public static class Builder {
        private AccountSafe data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  AccountSafe value for data.
         */
        public Builder(AccountSafe data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  AccountSafe value for data.
         * @return Builder
         */
        public Builder data(AccountSafe data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link CreateWalletResponse} object using the set fields.
         * @return {@link CreateWalletResponse}
         */
        public CreateWalletResponse build() {
            return new CreateWalletResponse(data);
        }
    }
}
