/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreatePaymentRequest type.
 */
public class CreatePaymentRequest {
    private String fromCurrency;
    private String toCurrency;
    private String fromAmount;
    private String toAmount;
    private String fromNetwork;
    private String toNetwork;
    private String organizationReferenceId;
    private String originatorAccountId;
    private String sourceAccountId;
    private String beneficiaryAccountId;

    /**
     * Default constructor.
     */
    public CreatePaymentRequest() {
    }

    /**
     * Initialization constructor.
     * @param  fromCurrency  String value for fromCurrency.
     * @param  toCurrency  String value for toCurrency.
     * @param  fromAmount  String value for fromAmount.
     * @param  toAmount  String value for toAmount.
     * @param  fromNetwork  String value for fromNetwork.
     * @param  toNetwork  String value for toNetwork.
     * @param  organizationReferenceId  String value for organizationReferenceId.
     * @param  originatorAccountId  String value for originatorAccountId.
     * @param  sourceAccountId  String value for sourceAccountId.
     * @param  beneficiaryAccountId  String value for beneficiaryAccountId.
     */
    public CreatePaymentRequest(
            String fromCurrency,
            String toCurrency,
            String fromAmount,
            String toAmount,
            String fromNetwork,
            String toNetwork,
            String organizationReferenceId,
            String originatorAccountId,
            String sourceAccountId,
            String beneficiaryAccountId) {
        this.fromCurrency = fromCurrency;
        this.toCurrency = toCurrency;
        this.fromAmount = fromAmount;
        this.toAmount = toAmount;
        this.fromNetwork = fromNetwork;
        this.toNetwork = toNetwork;
        this.organizationReferenceId = organizationReferenceId;
        this.originatorAccountId = originatorAccountId;
        this.sourceAccountId = sourceAccountId;
        this.beneficiaryAccountId = beneficiaryAccountId;
    }

    /**
     * Getter for FromCurrency.
     * Source currency code (e.g., 'USDC'). See GET /currencies for supported values.
     * @return Returns the String
     */
    @JsonGetter("from_currency")
    public String getFromCurrency() {
        return fromCurrency;
    }

    /**
     * Setter for FromCurrency.
     * Source currency code (e.g., 'USDC'). See GET /currencies for supported values.
     * @param fromCurrency Value for String
     */
    @JsonSetter("from_currency")
    public void setFromCurrency(String fromCurrency) {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Getter for ToCurrency.
     * Destination currency code (e.g., 'USD'). See GET /currencies for supported values.
     * @return Returns the String
     */
    @JsonGetter("to_currency")
    public String getToCurrency() {
        return toCurrency;
    }

    /**
     * Setter for ToCurrency.
     * Destination currency code (e.g., 'USD'). See GET /currencies for supported values.
     * @param toCurrency Value for String
     */
    @JsonSetter("to_currency")
    public void setToCurrency(String toCurrency) {
        this.toCurrency = toCurrency;
    }

    /**
     * Getter for FromAmount.
     * Amount to send in source currency units. Required if to_amount is not provided.
     * @return Returns the String
     */
    @JsonGetter("from_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFromAmount() {
        return fromAmount;
    }

    /**
     * Setter for FromAmount.
     * Amount to send in source currency units. Required if to_amount is not provided.
     * @param fromAmount Value for String
     */
    @JsonSetter("from_amount")
    public void setFromAmount(String fromAmount) {
        this.fromAmount = fromAmount;
    }

    /**
     * Getter for ToAmount.
     * Amount to receive in destination currency units. Required if from_amount is not provided.
     * @return Returns the String
     */
    @JsonGetter("to_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToAmount() {
        return toAmount;
    }

    /**
     * Setter for ToAmount.
     * Amount to receive in destination currency units. Required if from_amount is not provided.
     * @param toAmount Value for String
     */
    @JsonSetter("to_amount")
    public void setToAmount(String toAmount) {
        this.toAmount = toAmount;
    }

    /**
     * Getter for FromNetwork.
     * Blockchain network for source currency (e.g., 'POLYGON'). See GET /networks for supported
     * values.
     * @return Returns the String
     */
    @JsonGetter("from_network")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFromNetwork() {
        return fromNetwork;
    }

    /**
     * Setter for FromNetwork.
     * Blockchain network for source currency (e.g., 'POLYGON'). See GET /networks for supported
     * values.
     * @param fromNetwork Value for String
     */
    @JsonSetter("from_network")
    public void setFromNetwork(String fromNetwork) {
        this.fromNetwork = fromNetwork;
    }

    /**
     * Getter for ToNetwork.
     * Blockchain network for destination currency (if applicable). See GET /networks for supported
     * values.
     * @return Returns the String
     */
    @JsonGetter("to_network")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToNetwork() {
        return toNetwork;
    }

    /**
     * Setter for ToNetwork.
     * Blockchain network for destination currency (if applicable). See GET /networks for supported
     * values.
     * @param toNetwork Value for String
     */
    @JsonSetter("to_network")
    public void setToNetwork(String toNetwork) {
        this.toNetwork = toNetwork;
    }

    /**
     * Getter for OrganizationReferenceId.
     * Optional external reference ID for the organization.
     * @return Returns the String
     */
    @JsonGetter("organization_reference_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOrganizationReferenceId() {
        return organizationReferenceId;
    }

    /**
     * Setter for OrganizationReferenceId.
     * Optional external reference ID for the organization.
     * @param organizationReferenceId Value for String
     */
    @JsonSetter("organization_reference_id")
    public void setOrganizationReferenceId(String organizationReferenceId) {
        this.organizationReferenceId = organizationReferenceId;
    }

    /**
     * Getter for OriginatorAccountId.
     * ID of the account originating the payment.
     * @return Returns the String
     */
    @JsonGetter("originator_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOriginatorAccountId() {
        return originatorAccountId;
    }

    /**
     * Setter for OriginatorAccountId.
     * ID of the account originating the payment.
     * @param originatorAccountId Value for String
     */
    @JsonSetter("originator_account_id")
    public void setOriginatorAccountId(String originatorAccountId) {
        this.originatorAccountId = originatorAccountId;
    }

    /**
     * Getter for SourceAccountId.
     * ID of the source account (e.g., wallet).
     * @return Returns the String
     */
    @JsonGetter("source_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSourceAccountId() {
        return sourceAccountId;
    }

    /**
     * Setter for SourceAccountId.
     * ID of the source account (e.g., wallet).
     * @param sourceAccountId Value for String
     */
    @JsonSetter("source_account_id")
    public void setSourceAccountId(String sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    /**
     * Getter for BeneficiaryAccountId.
     * ID of the beneficiary account.
     * @return Returns the String
     */
    @JsonGetter("beneficiary_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBeneficiaryAccountId() {
        return beneficiaryAccountId;
    }

    /**
     * Setter for BeneficiaryAccountId.
     * ID of the beneficiary account.
     * @param beneficiaryAccountId Value for String
     */
    @JsonSetter("beneficiary_account_id")
    public void setBeneficiaryAccountId(String beneficiaryAccountId) {
        this.beneficiaryAccountId = beneficiaryAccountId;
    }

    /**
     * Converts this CreatePaymentRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreatePaymentRequest [" + "fromCurrency=" + fromCurrency + ", toCurrency="
                + toCurrency + ", fromAmount=" + fromAmount + ", toAmount=" + toAmount
                + ", fromNetwork=" + fromNetwork + ", toNetwork=" + toNetwork
                + ", organizationReferenceId=" + organizationReferenceId + ", originatorAccountId="
                + originatorAccountId + ", sourceAccountId=" + sourceAccountId
                + ", beneficiaryAccountId=" + beneficiaryAccountId + "]";
    }

    /**
     * Builds a new {@link CreatePaymentRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreatePaymentRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(fromCurrency, toCurrency)
                .fromAmount(getFromAmount())
                .toAmount(getToAmount())
                .fromNetwork(getFromNetwork())
                .toNetwork(getToNetwork())
                .organizationReferenceId(getOrganizationReferenceId())
                .originatorAccountId(getOriginatorAccountId())
                .sourceAccountId(getSourceAccountId())
                .beneficiaryAccountId(getBeneficiaryAccountId());
        return builder;
    }

    /**
     * Class to build instances of {@link CreatePaymentRequest}.
     */
    public static class Builder {
        private String fromCurrency;
        private String toCurrency;
        private String fromAmount;
        private String toAmount;
        private String fromNetwork;
        private String toNetwork;
        private String organizationReferenceId;
        private String originatorAccountId;
        private String sourceAccountId;
        private String beneficiaryAccountId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  fromCurrency  String value for fromCurrency.
         * @param  toCurrency  String value for toCurrency.
         */
        public Builder(String fromCurrency, String toCurrency) {
            this.fromCurrency = fromCurrency;
            this.toCurrency = toCurrency;
        }

        /**
         * Setter for fromCurrency.
         * @param  fromCurrency  String value for fromCurrency.
         * @return Builder
         */
        public Builder fromCurrency(String fromCurrency) {
            this.fromCurrency = fromCurrency;
            return this;
        }

        /**
         * Setter for toCurrency.
         * @param  toCurrency  String value for toCurrency.
         * @return Builder
         */
        public Builder toCurrency(String toCurrency) {
            this.toCurrency = toCurrency;
            return this;
        }

        /**
         * Setter for fromAmount.
         * @param  fromAmount  String value for fromAmount.
         * @return Builder
         */
        public Builder fromAmount(String fromAmount) {
            this.fromAmount = fromAmount;
            return this;
        }

        /**
         * Setter for toAmount.
         * @param  toAmount  String value for toAmount.
         * @return Builder
         */
        public Builder toAmount(String toAmount) {
            this.toAmount = toAmount;
            return this;
        }

        /**
         * Setter for fromNetwork.
         * @param  fromNetwork  String value for fromNetwork.
         * @return Builder
         */
        public Builder fromNetwork(String fromNetwork) {
            this.fromNetwork = fromNetwork;
            return this;
        }

        /**
         * Setter for toNetwork.
         * @param  toNetwork  String value for toNetwork.
         * @return Builder
         */
        public Builder toNetwork(String toNetwork) {
            this.toNetwork = toNetwork;
            return this;
        }

        /**
         * Setter for organizationReferenceId.
         * @param  organizationReferenceId  String value for organizationReferenceId.
         * @return Builder
         */
        public Builder organizationReferenceId(String organizationReferenceId) {
            this.organizationReferenceId = organizationReferenceId;
            return this;
        }

        /**
         * Setter for originatorAccountId.
         * @param  originatorAccountId  String value for originatorAccountId.
         * @return Builder
         */
        public Builder originatorAccountId(String originatorAccountId) {
            this.originatorAccountId = originatorAccountId;
            return this;
        }

        /**
         * Setter for sourceAccountId.
         * @param  sourceAccountId  String value for sourceAccountId.
         * @return Builder
         */
        public Builder sourceAccountId(String sourceAccountId) {
            this.sourceAccountId = sourceAccountId;
            return this;
        }

        /**
         * Setter for beneficiaryAccountId.
         * @param  beneficiaryAccountId  String value for beneficiaryAccountId.
         * @return Builder
         */
        public Builder beneficiaryAccountId(String beneficiaryAccountId) {
            this.beneficiaryAccountId = beneficiaryAccountId;
            return this;
        }

        /**
         * Builds a new {@link CreatePaymentRequest} object using the set fields.
         * @return {@link CreatePaymentRequest}
         */
        public CreatePaymentRequest build() {
            return new CreatePaymentRequest(fromCurrency, toCurrency, fromAmount, toAmount,
                    fromNetwork, toNetwork, organizationReferenceId, originatorAccountId,
                    sourceAccountId, beneficiaryAccountId);
        }
    }
}
