/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateWalletRequest type.
 */
public class CreateWalletRequest {
    private String workspaceId;
    private String tenantId;
    private String counterpartyId;
    private String name;
    private Type3Enum type;
    private String signature;

    /**
     * Default constructor.
     */
    public CreateWalletRequest() {
    }

    /**
     * Initialization constructor.
     * @param  workspaceId  String value for workspaceId.
     * @param  name  String value for name.
     * @param  type  Type3Enum value for type.
     * @param  signature  String value for signature.
     * @param  tenantId  String value for tenantId.
     * @param  counterpartyId  String value for counterpartyId.
     */
    public CreateWalletRequest(
            String workspaceId,
            String name,
            Type3Enum type,
            String signature,
            String tenantId,
            String counterpartyId) {
        this.workspaceId = workspaceId;
        this.tenantId = tenantId;
        this.counterpartyId = counterpartyId;
        this.name = name;
        this.type = type;
        this.signature = signature;
    }

    /**
     * Getter for WorkspaceId.
     * ID of the workspace.
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * ID of the workspace.
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for TenantId.
     * ID of the tenant that owns this wallet (optional). At most one of tenant_id or
     * counterparty_id may be provided.
     * @return Returns the String
     */
    @JsonGetter("tenant_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Setter for TenantId.
     * ID of the tenant that owns this wallet (optional). At most one of tenant_id or
     * counterparty_id may be provided.
     * @param tenantId Value for String
     */
    @JsonSetter("tenant_id")
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Getter for CounterpartyId.
     * ID of the counterparty that owns this wallet (optional). At most one of tenant_id or
     * counterparty_id may be provided.
     * @return Returns the String
     */
    @JsonGetter("counterparty_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCounterpartyId() {
        return counterpartyId;
    }

    /**
     * Setter for CounterpartyId.
     * ID of the counterparty that owns this wallet (optional). At most one of tenant_id or
     * counterparty_id may be provided.
     * @param counterpartyId Value for String
     */
    @JsonSetter("counterparty_id")
    public void setCounterpartyId(String counterpartyId) {
        this.counterpartyId = counterpartyId;
    }

    /**
     * Getter for Name.
     * Name of the wallet account.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of the wallet account.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Type.
     * Wallet type.
     * @return Returns the Type3Enum
     */
    @JsonGetter("type")
    public Type3Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Wallet type.
     * @param type Value for Type3Enum
     */
    @JsonSetter("type")
    public void setType(Type3Enum type) {
        this.type = type;
    }

    /**
     * Getter for Signature.
     * A cryptographic stamp used to verify the integrity and authenticity of the request. This
     * ensures the request was signed by an authorized key. See Documentation &gt; Signing for more
     * details.
     * @return Returns the String
     */
    @JsonGetter("signature")
    public String getSignature() {
        return signature;
    }

    /**
     * Setter for Signature.
     * A cryptographic stamp used to verify the integrity and authenticity of the request. This
     * ensures the request was signed by an authorized key. See Documentation &gt; Signing for more
     * details.
     * @param signature Value for String
     */
    @JsonSetter("signature")
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Converts this CreateWalletRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateWalletRequest [" + "workspaceId=" + workspaceId + ", name=" + name + ", type="
                + type + ", signature=" + signature + ", tenantId=" + tenantId + ", counterpartyId="
                + counterpartyId + "]";
    }

    /**
     * Builds a new {@link CreateWalletRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateWalletRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(workspaceId, name, type, signature)
                .tenantId(getTenantId())
                .counterpartyId(getCounterpartyId());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateWalletRequest}.
     */
    public static class Builder {
        private String workspaceId;
        private String name;
        private Type3Enum type;
        private String signature;
        private String tenantId;
        private String counterpartyId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  workspaceId  String value for workspaceId.
         * @param  name  String value for name.
         * @param  type  Type3Enum value for type.
         * @param  signature  String value for signature.
         */
        public Builder(String workspaceId, String name, Type3Enum type, String signature) {
            this.workspaceId = workspaceId;
            this.name = name;
            this.type = type;
            this.signature = signature;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  Type3Enum value for type.
         * @return Builder
         */
        public Builder type(Type3Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for signature.
         * @param  signature  String value for signature.
         * @return Builder
         */
        public Builder signature(String signature) {
            this.signature = signature;
            return this;
        }

        /**
         * Setter for tenantId.
         * @param  tenantId  String value for tenantId.
         * @return Builder
         */
        public Builder tenantId(String tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        /**
         * Setter for counterpartyId.
         * @param  counterpartyId  String value for counterpartyId.
         * @return Builder
         */
        public Builder counterpartyId(String counterpartyId) {
            this.counterpartyId = counterpartyId;
            return this;
        }

        /**
         * Builds a new {@link CreateWalletRequest} object using the set fields.
         * @return {@link CreateWalletRequest}
         */
        public CreateWalletRequest build() {
            return new CreateWalletRequest(workspaceId, name, type, signature, tenantId,
                    counterpartyId);
        }
    }
}
