/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateBankRequest type.
 */
public class CreateBankRequest {
    private String workspaceId;
    private String name;
    private String bankName;
    private String bankCodeType;
    private String bankIdentifierCode;
    private String bankAccountNumber;
    private String counterpartyId;

    /**
     * Default constructor.
     */
    public CreateBankRequest() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  bankName  String value for bankName.
     * @param  bankCodeType  String value for bankCodeType.
     * @param  bankIdentifierCode  String value for bankIdentifierCode.
     * @param  bankAccountNumber  String value for bankAccountNumber.
     * @param  workspaceId  String value for workspaceId.
     * @param  counterpartyId  String value for counterpartyId.
     */
    public CreateBankRequest(
            String name,
            String bankName,
            String bankCodeType,
            String bankIdentifierCode,
            String bankAccountNumber,
            String workspaceId,
            String counterpartyId) {
        this.workspaceId = workspaceId;
        this.name = name;
        this.bankName = bankName;
        this.bankCodeType = bankCodeType;
        this.bankIdentifierCode = bankIdentifierCode;
        this.bankAccountNumber = bankAccountNumber;
        this.counterpartyId = counterpartyId;
    }

    /**
     * Getter for WorkspaceId.
     * ID of the workspace.
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * ID of the workspace.
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for Name.
     * Name of the bank account.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of the bank account.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for BankName.
     * Name of the bank.
     * @return Returns the String
     */
    @JsonGetter("bank_name")
    public String getBankName() {
        return bankName;
    }

    /**
     * Setter for BankName.
     * Name of the bank.
     * @param bankName Value for String
     */
    @JsonSetter("bank_name")
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * Getter for BankCodeType.
     * Type of bank code (e.g., 'SWIFT').
     * @return Returns the String
     */
    @JsonGetter("bank_code_type")
    public String getBankCodeType() {
        return bankCodeType;
    }

    /**
     * Setter for BankCodeType.
     * Type of bank code (e.g., 'SWIFT').
     * @param bankCodeType Value for String
     */
    @JsonSetter("bank_code_type")
    public void setBankCodeType(String bankCodeType) {
        this.bankCodeType = bankCodeType;
    }

    /**
     * Getter for BankIdentifierCode.
     * Bank identifier code value.
     * @return Returns the String
     */
    @JsonGetter("bank_identifier_code")
    public String getBankIdentifierCode() {
        return bankIdentifierCode;
    }

    /**
     * Setter for BankIdentifierCode.
     * Bank identifier code value.
     * @param bankIdentifierCode Value for String
     */
    @JsonSetter("bank_identifier_code")
    public void setBankIdentifierCode(String bankIdentifierCode) {
        this.bankIdentifierCode = bankIdentifierCode;
    }

    /**
     * Getter for BankAccountNumber.
     * Bank account number (IBAN, etc).
     * @return Returns the String
     */
    @JsonGetter("bank_account_number")
    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * Setter for BankAccountNumber.
     * Bank account number (IBAN, etc).
     * @param bankAccountNumber Value for String
     */
    @JsonSetter("bank_account_number")
    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    /**
     * Getter for CounterpartyId.
     * ID of the counterparty owner.
     * @return Returns the String
     */
    @JsonGetter("counterparty_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCounterpartyId() {
        return counterpartyId;
    }

    /**
     * Setter for CounterpartyId.
     * ID of the counterparty owner.
     * @param counterpartyId Value for String
     */
    @JsonSetter("counterparty_id")
    public void setCounterpartyId(String counterpartyId) {
        this.counterpartyId = counterpartyId;
    }

    /**
     * Converts this CreateBankRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateBankRequest [" + "name=" + name + ", bankName=" + bankName + ", bankCodeType="
                + bankCodeType + ", bankIdentifierCode=" + bankIdentifierCode
                + ", bankAccountNumber=" + bankAccountNumber + ", workspaceId=" + workspaceId
                + ", counterpartyId=" + counterpartyId + "]";
    }

    /**
     * Builds a new {@link CreateBankRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateBankRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, bankName, bankCodeType, bankIdentifierCode,
                bankAccountNumber)
                .workspaceId(getWorkspaceId())
                .counterpartyId(getCounterpartyId());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateBankRequest}.
     */
    public static class Builder {
        private String name;
        private String bankName;
        private String bankCodeType;
        private String bankIdentifierCode;
        private String bankAccountNumber;
        private String workspaceId;
        private String counterpartyId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  bankName  String value for bankName.
         * @param  bankCodeType  String value for bankCodeType.
         * @param  bankIdentifierCode  String value for bankIdentifierCode.
         * @param  bankAccountNumber  String value for bankAccountNumber.
         */
        public Builder(String name, String bankName, String bankCodeType, String bankIdentifierCode,
                String bankAccountNumber) {
            this.name = name;
            this.bankName = bankName;
            this.bankCodeType = bankCodeType;
            this.bankIdentifierCode = bankIdentifierCode;
            this.bankAccountNumber = bankAccountNumber;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for bankName.
         * @param  bankName  String value for bankName.
         * @return Builder
         */
        public Builder bankName(String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Setter for bankCodeType.
         * @param  bankCodeType  String value for bankCodeType.
         * @return Builder
         */
        public Builder bankCodeType(String bankCodeType) {
            this.bankCodeType = bankCodeType;
            return this;
        }

        /**
         * Setter for bankIdentifierCode.
         * @param  bankIdentifierCode  String value for bankIdentifierCode.
         * @return Builder
         */
        public Builder bankIdentifierCode(String bankIdentifierCode) {
            this.bankIdentifierCode = bankIdentifierCode;
            return this;
        }

        /**
         * Setter for bankAccountNumber.
         * @param  bankAccountNumber  String value for bankAccountNumber.
         * @return Builder
         */
        public Builder bankAccountNumber(String bankAccountNumber) {
            this.bankAccountNumber = bankAccountNumber;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for counterpartyId.
         * @param  counterpartyId  String value for counterpartyId.
         * @return Builder
         */
        public Builder counterpartyId(String counterpartyId) {
            this.counterpartyId = counterpartyId;
            return this;
        }

        /**
         * Builds a new {@link CreateBankRequest} object using the set fields.
         * @return {@link CreateBankRequest}
         */
        public CreateBankRequest build() {
            return new CreateBankRequest(name, bankName, bankCodeType, bankIdentifierCode,
                    bankAccountNumber, workspaceId, counterpartyId);
        }
    }
}
