/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessAddressCountry;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessCity;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessDba;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessLegalEntityIdentifier;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessLegalName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessState;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessStreetAddress1;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyBusinessStreetAddress2;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualAddressCountry;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualCity;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualDateOfBirth;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualFirstName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualLastName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualNationalIdentificationNumber;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualPostalCode;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualState;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualStreetAddress1;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyIndividualStreetAddress2;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.CounterpartyTenantId;

/**
 * This is a model class for Data type.
 */
public class Data
        extends Counterparty {

    /**
     * Default constructor.
     */
    public Data() {
        super();
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  workspaceId  String value for workspaceId.
     * @param  classification  ClassificationEnum value for classification.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     * @param  tenantId  CounterpartyTenantId value for tenantId.
     * @param  individualFirstName  CounterpartyIndividualFirstName value for individualFirstName.
     * @param  individualLastName  CounterpartyIndividualLastName value for individualLastName.
     * @param  individualAddressCountry  CounterpartyIndividualAddressCountry value for
     *         individualAddressCountry.
     * @param  individualDateOfBirth  CounterpartyIndividualDateOfBirth value for
     *         individualDateOfBirth.
     * @param  individualNationalIdentificationNumber
     *         CounterpartyIndividualNationalIdentificationNumber value for
     *         individualNationalIdentificationNumber.
     * @param  individualStreetAddress1  CounterpartyIndividualStreetAddress1 value for
     *         individualStreetAddress1.
     * @param  individualStreetAddress2  CounterpartyIndividualStreetAddress2 value for
     *         individualStreetAddress2.
     * @param  individualCity  CounterpartyIndividualCity value for individualCity.
     * @param  individualState  CounterpartyIndividualState value for individualState.
     * @param  individualPostalCode  CounterpartyIndividualPostalCode value for
     *         individualPostalCode.
     * @param  businessLegalName  CounterpartyBusinessLegalName value for businessLegalName.
     * @param  businessDba  CounterpartyBusinessDba value for businessDba.
     * @param  businessAddressCountry  CounterpartyBusinessAddressCountry value for
     *         businessAddressCountry.
     * @param  businessStreetAddress1  CounterpartyBusinessStreetAddress1 value for
     *         businessStreetAddress1.
     * @param  businessStreetAddress2  CounterpartyBusinessStreetAddress2 value for
     *         businessStreetAddress2.
     * @param  businessCity  CounterpartyBusinessCity value for businessCity.
     * @param  businessState  CounterpartyBusinessState value for businessState.
     * @param  businessLegalEntityIdentifier  CounterpartyBusinessLegalEntityIdentifier value for
     *         businessLegalEntityIdentifier.
     */
    public Data(
            String id,
            String workspaceId,
            ClassificationEnum classification,
            String createdAt,
            String updatedAt,
            CounterpartyTenantId tenantId,
            CounterpartyIndividualFirstName individualFirstName,
            CounterpartyIndividualLastName individualLastName,
            CounterpartyIndividualAddressCountry individualAddressCountry,
            CounterpartyIndividualDateOfBirth individualDateOfBirth,
            CounterpartyIndividualNationalIdentificationNumber individualNationalIdentificationNumber,
            CounterpartyIndividualStreetAddress1 individualStreetAddress1,
            CounterpartyIndividualStreetAddress2 individualStreetAddress2,
            CounterpartyIndividualCity individualCity,
            CounterpartyIndividualState individualState,
            CounterpartyIndividualPostalCode individualPostalCode,
            CounterpartyBusinessLegalName businessLegalName,
            CounterpartyBusinessDba businessDba,
            CounterpartyBusinessAddressCountry businessAddressCountry,
            CounterpartyBusinessStreetAddress1 businessStreetAddress1,
            CounterpartyBusinessStreetAddress2 businessStreetAddress2,
            CounterpartyBusinessCity businessCity,
            CounterpartyBusinessState businessState,
            CounterpartyBusinessLegalEntityIdentifier businessLegalEntityIdentifier) {
        super(id, workspaceId, classification, createdAt, updatedAt, tenantId, individualFirstName,
                individualLastName, individualAddressCountry, individualDateOfBirth,
                individualNationalIdentificationNumber, individualStreetAddress1,
                individualStreetAddress2, individualCity, individualState, individualPostalCode,
                businessLegalName, businessDba, businessAddressCountry, businessStreetAddress1,
                businessStreetAddress2, businessCity, businessState,
                businessLegalEntityIdentifier);
    }

    /**
     * Converts this Data into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data [" + "id=" + getId() + ", workspaceId=" + getWorkspaceId()
                + ", classification=" + getClassification() + ", createdAt=" + getCreatedAt()
                + ", updatedAt=" + getUpdatedAt() + ", tenantId=" + getTenantId()
                + ", individualFirstName=" + getIndividualFirstName() + ", individualLastName="
                + getIndividualLastName() + ", individualAddressCountry="
                + getIndividualAddressCountry() + ", individualDateOfBirth="
                + getIndividualDateOfBirth() + ", individualNationalIdentificationNumber="
                + getIndividualNationalIdentificationNumber() + ", individualStreetAddress1="
                + getIndividualStreetAddress1() + ", individualStreetAddress2="
                + getIndividualStreetAddress2() + ", individualCity=" + getIndividualCity()
                + ", individualState=" + getIndividualState() + ", individualPostalCode="
                + getIndividualPostalCode() + ", businessLegalName=" + getBusinessLegalName()
                + ", businessDba=" + getBusinessDba() + ", businessAddressCountry="
                + getBusinessAddressCountry() + ", businessStreetAddress1="
                + getBusinessStreetAddress1() + ", businessStreetAddress2="
                + getBusinessStreetAddress2() + ", businessCity=" + getBusinessCity()
                + ", businessState=" + getBusinessState() + ", businessLegalEntityIdentifier="
                + getBusinessLegalEntityIdentifier() + "]";
    }

    /**
     * Builds a new {@link Data.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data.Builder} object
     */
    public Builder toDataBuilder() {
        Builder builder = new Builder(getId(), getWorkspaceId(), getClassification(),
                getCreatedAt(), getUpdatedAt())
                .tenantId(getTenantId())
                .individualFirstName(getIndividualFirstName())
                .individualLastName(getIndividualLastName())
                .individualAddressCountry(getIndividualAddressCountry())
                .individualDateOfBirth(getIndividualDateOfBirth())
                .individualNationalIdentificationNumber(getIndividualNationalIdentificationNumber())
                .individualStreetAddress1(getIndividualStreetAddress1())
                .individualStreetAddress2(getIndividualStreetAddress2())
                .individualCity(getIndividualCity())
                .individualState(getIndividualState())
                .individualPostalCode(getIndividualPostalCode())
                .businessLegalName(getBusinessLegalName())
                .businessDba(getBusinessDba())
                .businessAddressCountry(getBusinessAddressCountry())
                .businessStreetAddress1(getBusinessStreetAddress1())
                .businessStreetAddress2(getBusinessStreetAddress2())
                .businessCity(getBusinessCity())
                .businessState(getBusinessState())
                .businessLegalEntityIdentifier(getBusinessLegalEntityIdentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link Data}.
     */
    public static class Builder {
        private String id;
        private String workspaceId;
        private ClassificationEnum classification;
        private String createdAt;
        private String updatedAt;
        private CounterpartyTenantId tenantId;
        private CounterpartyIndividualFirstName individualFirstName;
        private CounterpartyIndividualLastName individualLastName;
        private CounterpartyIndividualAddressCountry individualAddressCountry;
        private CounterpartyIndividualDateOfBirth individualDateOfBirth;
        private CounterpartyIndividualNationalIdentificationNumber individualNationalIdentificationNumber;
        private CounterpartyIndividualStreetAddress1 individualStreetAddress1;
        private CounterpartyIndividualStreetAddress2 individualStreetAddress2;
        private CounterpartyIndividualCity individualCity;
        private CounterpartyIndividualState individualState;
        private CounterpartyIndividualPostalCode individualPostalCode;
        private CounterpartyBusinessLegalName businessLegalName;
        private CounterpartyBusinessDba businessDba;
        private CounterpartyBusinessAddressCountry businessAddressCountry;
        private CounterpartyBusinessStreetAddress1 businessStreetAddress1;
        private CounterpartyBusinessStreetAddress2 businessStreetAddress2;
        private CounterpartyBusinessCity businessCity;
        private CounterpartyBusinessState businessState;
        private CounterpartyBusinessLegalEntityIdentifier businessLegalEntityIdentifier;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  workspaceId  String value for workspaceId.
         * @param  classification  ClassificationEnum value for classification.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         */
        public Builder(String id, String workspaceId, ClassificationEnum classification,
                String createdAt, String updatedAt) {
            this.id = id;
            this.workspaceId = workspaceId;
            this.classification = classification;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for classification.
         * @param  classification  ClassificationEnum value for classification.
         * @return Builder
         */
        public Builder classification(ClassificationEnum classification) {
            this.classification = classification;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for tenantId.
         * @param  tenantId  CounterpartyTenantId value for tenantId.
         * @return Builder
         */
        public Builder tenantId(CounterpartyTenantId tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        /**
         * Setter for individualFirstName.
         * @param  individualFirstName  CounterpartyIndividualFirstName value for
         *         individualFirstName.
         * @return Builder
         */
        public Builder individualFirstName(CounterpartyIndividualFirstName individualFirstName) {
            this.individualFirstName = individualFirstName;
            return this;
        }

        /**
         * Setter for individualLastName.
         * @param  individualLastName  CounterpartyIndividualLastName value for individualLastName.
         * @return Builder
         */
        public Builder individualLastName(CounterpartyIndividualLastName individualLastName) {
            this.individualLastName = individualLastName;
            return this;
        }

        /**
         * Setter for individualAddressCountry.
         * @param  individualAddressCountry  CounterpartyIndividualAddressCountry value for
         *         individualAddressCountry.
         * @return Builder
         */
        public Builder individualAddressCountry(
                CounterpartyIndividualAddressCountry individualAddressCountry) {
            this.individualAddressCountry = individualAddressCountry;
            return this;
        }

        /**
         * Setter for individualDateOfBirth.
         * @param  individualDateOfBirth  CounterpartyIndividualDateOfBirth value for
         *         individualDateOfBirth.
         * @return Builder
         */
        public Builder individualDateOfBirth(
                CounterpartyIndividualDateOfBirth individualDateOfBirth) {
            this.individualDateOfBirth = individualDateOfBirth;
            return this;
        }

        /**
         * Setter for individualNationalIdentificationNumber.
         * @param  individualNationalIdentificationNumber
         *         CounterpartyIndividualNationalIdentificationNumber value for
         *         individualNationalIdentificationNumber.
         * @return Builder
         */
        public Builder individualNationalIdentificationNumber(
                CounterpartyIndividualNationalIdentificationNumber individualNationalIdentificationNumber) {
            this.individualNationalIdentificationNumber = individualNationalIdentificationNumber;
            return this;
        }

        /**
         * Setter for individualStreetAddress1.
         * @param  individualStreetAddress1  CounterpartyIndividualStreetAddress1 value for
         *         individualStreetAddress1.
         * @return Builder
         */
        public Builder individualStreetAddress1(
                CounterpartyIndividualStreetAddress1 individualStreetAddress1) {
            this.individualStreetAddress1 = individualStreetAddress1;
            return this;
        }

        /**
         * Setter for individualStreetAddress2.
         * @param  individualStreetAddress2  CounterpartyIndividualStreetAddress2 value for
         *         individualStreetAddress2.
         * @return Builder
         */
        public Builder individualStreetAddress2(
                CounterpartyIndividualStreetAddress2 individualStreetAddress2) {
            this.individualStreetAddress2 = individualStreetAddress2;
            return this;
        }

        /**
         * Setter for individualCity.
         * @param  individualCity  CounterpartyIndividualCity value for individualCity.
         * @return Builder
         */
        public Builder individualCity(CounterpartyIndividualCity individualCity) {
            this.individualCity = individualCity;
            return this;
        }

        /**
         * Setter for individualState.
         * @param  individualState  CounterpartyIndividualState value for individualState.
         * @return Builder
         */
        public Builder individualState(CounterpartyIndividualState individualState) {
            this.individualState = individualState;
            return this;
        }

        /**
         * Setter for individualPostalCode.
         * @param  individualPostalCode  CounterpartyIndividualPostalCode value for
         *         individualPostalCode.
         * @return Builder
         */
        public Builder individualPostalCode(
                CounterpartyIndividualPostalCode individualPostalCode) {
            this.individualPostalCode = individualPostalCode;
            return this;
        }

        /**
         * Setter for businessLegalName.
         * @param  businessLegalName  CounterpartyBusinessLegalName value for businessLegalName.
         * @return Builder
         */
        public Builder businessLegalName(CounterpartyBusinessLegalName businessLegalName) {
            this.businessLegalName = businessLegalName;
            return this;
        }

        /**
         * Setter for businessDba.
         * @param  businessDba  CounterpartyBusinessDba value for businessDba.
         * @return Builder
         */
        public Builder businessDba(CounterpartyBusinessDba businessDba) {
            this.businessDba = businessDba;
            return this;
        }

        /**
         * Setter for businessAddressCountry.
         * @param  businessAddressCountry  CounterpartyBusinessAddressCountry value for
         *         businessAddressCountry.
         * @return Builder
         */
        public Builder businessAddressCountry(
                CounterpartyBusinessAddressCountry businessAddressCountry) {
            this.businessAddressCountry = businessAddressCountry;
            return this;
        }

        /**
         * Setter for businessStreetAddress1.
         * @param  businessStreetAddress1  CounterpartyBusinessStreetAddress1 value for
         *         businessStreetAddress1.
         * @return Builder
         */
        public Builder businessStreetAddress1(
                CounterpartyBusinessStreetAddress1 businessStreetAddress1) {
            this.businessStreetAddress1 = businessStreetAddress1;
            return this;
        }

        /**
         * Setter for businessStreetAddress2.
         * @param  businessStreetAddress2  CounterpartyBusinessStreetAddress2 value for
         *         businessStreetAddress2.
         * @return Builder
         */
        public Builder businessStreetAddress2(
                CounterpartyBusinessStreetAddress2 businessStreetAddress2) {
            this.businessStreetAddress2 = businessStreetAddress2;
            return this;
        }

        /**
         * Setter for businessCity.
         * @param  businessCity  CounterpartyBusinessCity value for businessCity.
         * @return Builder
         */
        public Builder businessCity(CounterpartyBusinessCity businessCity) {
            this.businessCity = businessCity;
            return this;
        }

        /**
         * Setter for businessState.
         * @param  businessState  CounterpartyBusinessState value for businessState.
         * @return Builder
         */
        public Builder businessState(CounterpartyBusinessState businessState) {
            this.businessState = businessState;
            return this;
        }

        /**
         * Setter for businessLegalEntityIdentifier.
         * @param  businessLegalEntityIdentifier  CounterpartyBusinessLegalEntityIdentifier value
         *         for businessLegalEntityIdentifier.
         * @return Builder
         */
        public Builder businessLegalEntityIdentifier(
                CounterpartyBusinessLegalEntityIdentifier businessLegalEntityIdentifier) {
            this.businessLegalEntityIdentifier = businessLegalEntityIdentifier;
            return this;
        }

        /**
         * Builds a new {@link Data} object using the set fields.
         * @return {@link Data}
         */
        public Data build() {
            return new Data(id, workspaceId, classification, createdAt, updatedAt, tenantId,
                    individualFirstName, individualLastName, individualAddressCountry,
                    individualDateOfBirth, individualNationalIdentificationNumber,
                    individualStreetAddress1, individualStreetAddress2, individualCity,
                    individualState, individualPostalCode, businessLegalName, businessDba,
                    businessAddressCountry, businessStreetAddress1, businessStreetAddress2,
                    businessCity, businessState, businessLegalEntityIdentifier);
        }
    }
}
