/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.DateTimeHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7BalanceReservedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7BalanceStatus;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7BeneficiaryAccountId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7FromNetwork;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7OrganizationReferenceId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7OriginatorAccountId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7RiskReviewedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7RiskReviewedBy;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7RiskStatusReasons;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7SourceAccountId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.Data7ToNetwork;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;

/**
 * This is a model class for Data7 type.
 */
public class Data7 {
    private String id;
    private String workspaceId;
    private Data7OrganizationReferenceId organizationReferenceId;
    private Direction1Enum direction;
    private PaymentTypeEnum paymentType;
    private Data7SourceAccountId sourceAccountId;
    private Data7OriginatorAccountId originatorAccountId;
    private Data7BeneficiaryAccountId beneficiaryAccountId;
    private String fromAmount;
    private String fromCurrency;
    private Data7FromNetwork fromNetwork;
    private String toAmount;
    private String toCurrency;
    private Data7ToNetwork toNetwork;
    private RiskStatusEnum riskStatus;
    private Data7RiskStatusReasons riskStatusReasons;
    private Data7RiskReviewedBy riskReviewedBy;
    private Data7RiskReviewedAt riskReviewedAt;
    private Data7BalanceStatus balanceStatus;
    private Data7BalanceReservedAt balanceReservedAt;
    private List<Step> steps;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime expiresAt;

    /**
     * Default constructor.
     */
    public Data7() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  workspaceId  String value for workspaceId.
     * @param  direction  Direction1Enum value for direction.
     * @param  paymentType  PaymentTypeEnum value for paymentType.
     * @param  fromAmount  String value for fromAmount.
     * @param  fromCurrency  String value for fromCurrency.
     * @param  toAmount  String value for toAmount.
     * @param  toCurrency  String value for toCurrency.
     * @param  riskStatus  RiskStatusEnum value for riskStatus.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  updatedAt  LocalDateTime value for updatedAt.
     * @param  expiresAt  LocalDateTime value for expiresAt.
     * @param  organizationReferenceId  Data7OrganizationReferenceId value for
     *         organizationReferenceId.
     * @param  sourceAccountId  Data7SourceAccountId value for sourceAccountId.
     * @param  originatorAccountId  Data7OriginatorAccountId value for originatorAccountId.
     * @param  beneficiaryAccountId  Data7BeneficiaryAccountId value for beneficiaryAccountId.
     * @param  fromNetwork  Data7FromNetwork value for fromNetwork.
     * @param  toNetwork  Data7ToNetwork value for toNetwork.
     * @param  riskStatusReasons  Data7RiskStatusReasons value for riskStatusReasons.
     * @param  riskReviewedBy  Data7RiskReviewedBy value for riskReviewedBy.
     * @param  riskReviewedAt  Data7RiskReviewedAt value for riskReviewedAt.
     * @param  balanceStatus  Data7BalanceStatus value for balanceStatus.
     * @param  balanceReservedAt  Data7BalanceReservedAt value for balanceReservedAt.
     * @param  steps  List of Step value for steps.
     */
    public Data7(
            String id,
            String workspaceId,
            Direction1Enum direction,
            PaymentTypeEnum paymentType,
            String fromAmount,
            String fromCurrency,
            String toAmount,
            String toCurrency,
            RiskStatusEnum riskStatus,
            LocalDateTime createdAt,
            LocalDateTime updatedAt,
            LocalDateTime expiresAt,
            Data7OrganizationReferenceId organizationReferenceId,
            Data7SourceAccountId sourceAccountId,
            Data7OriginatorAccountId originatorAccountId,
            Data7BeneficiaryAccountId beneficiaryAccountId,
            Data7FromNetwork fromNetwork,
            Data7ToNetwork toNetwork,
            Data7RiskStatusReasons riskStatusReasons,
            Data7RiskReviewedBy riskReviewedBy,
            Data7RiskReviewedAt riskReviewedAt,
            Data7BalanceStatus balanceStatus,
            Data7BalanceReservedAt balanceReservedAt,
            List<Step> steps) {
        this.id = id;
        this.workspaceId = workspaceId;
        this.organizationReferenceId = organizationReferenceId;
        this.direction = direction;
        this.paymentType = paymentType;
        this.sourceAccountId = sourceAccountId;
        this.originatorAccountId = originatorAccountId;
        this.beneficiaryAccountId = beneficiaryAccountId;
        this.fromAmount = fromAmount;
        this.fromCurrency = fromCurrency;
        this.fromNetwork = fromNetwork;
        this.toAmount = toAmount;
        this.toCurrency = toCurrency;
        this.toNetwork = toNetwork;
        this.riskStatus = riskStatus;
        this.riskStatusReasons = riskStatusReasons;
        this.riskReviewedBy = riskReviewedBy;
        this.riskReviewedAt = riskReviewedAt;
        this.balanceStatus = balanceStatus;
        this.balanceReservedAt = balanceReservedAt;
        this.steps = steps;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for Id.
     * Unique identifier for the payment
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for the payment
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for WorkspaceId.
     * Workspace ID the payment belongs to
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * Workspace ID the payment belongs to
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for OrganizationReferenceId.
     * Optional external reference ID.
     * @return Returns the Data7OrganizationReferenceId
     */
    @JsonGetter("organization_reference_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7OrganizationReferenceId getOrganizationReferenceId() {
        return organizationReferenceId;
    }

    /**
     * Setter for OrganizationReferenceId.
     * Optional external reference ID.
     * @param organizationReferenceId Value for Data7OrganizationReferenceId
     */
    @JsonSetter("organization_reference_id")
    public void setOrganizationReferenceId(Data7OrganizationReferenceId organizationReferenceId) {
        this.organizationReferenceId = organizationReferenceId;
    }

    /**
     * Getter for Direction.
     * Payment direction: 'inbound', 'outbound', 'internal'
     * @return Returns the Direction1Enum
     */
    @JsonGetter("direction")
    public Direction1Enum getDirection() {
        return direction;
    }

    /**
     * Setter for Direction.
     * Payment direction: 'inbound', 'outbound', 'internal'
     * @param direction Value for Direction1Enum
     */
    @JsonSetter("direction")
    public void setDirection(Direction1Enum direction) {
        this.direction = direction;
    }

    /**
     * Getter for PaymentType.
     * Type of payment operation: 'payment' (wallet-to-wallet), 'offramp' (crypto-to-fiat), 'onramp'
     * (fiat-to-crypto), 'withdrawal', 'deposit', or 'transfer'.
     * @return Returns the PaymentTypeEnum
     */
    @JsonGetter("payment_type")
    public PaymentTypeEnum getPaymentType() {
        return paymentType;
    }

    /**
     * Setter for PaymentType.
     * Type of payment operation: 'payment' (wallet-to-wallet), 'offramp' (crypto-to-fiat), 'onramp'
     * (fiat-to-crypto), 'withdrawal', 'deposit', or 'transfer'.
     * @param paymentType Value for PaymentTypeEnum
     */
    @JsonSetter("payment_type")
    public void setPaymentType(PaymentTypeEnum paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * Getter for SourceAccountId.
     * ID of the source account (paying wallet).
     * @return Returns the Data7SourceAccountId
     */
    @JsonGetter("source_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7SourceAccountId getSourceAccountId() {
        return sourceAccountId;
    }

    /**
     * Setter for SourceAccountId.
     * ID of the source account (paying wallet).
     * @param sourceAccountId Value for Data7SourceAccountId
     */
    @JsonSetter("source_account_id")
    public void setSourceAccountId(Data7SourceAccountId sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    /**
     * Getter for OriginatorAccountId.
     * ID of the originator account.
     * @return Returns the Data7OriginatorAccountId
     */
    @JsonGetter("originator_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7OriginatorAccountId getOriginatorAccountId() {
        return originatorAccountId;
    }

    /**
     * Setter for OriginatorAccountId.
     * ID of the originator account.
     * @param originatorAccountId Value for Data7OriginatorAccountId
     */
    @JsonSetter("originator_account_id")
    public void setOriginatorAccountId(Data7OriginatorAccountId originatorAccountId) {
        this.originatorAccountId = originatorAccountId;
    }

    /**
     * Getter for BeneficiaryAccountId.
     * ID of the beneficiary account.
     * @return Returns the Data7BeneficiaryAccountId
     */
    @JsonGetter("beneficiary_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7BeneficiaryAccountId getBeneficiaryAccountId() {
        return beneficiaryAccountId;
    }

    /**
     * Setter for BeneficiaryAccountId.
     * ID of the beneficiary account.
     * @param beneficiaryAccountId Value for Data7BeneficiaryAccountId
     */
    @JsonSetter("beneficiary_account_id")
    public void setBeneficiaryAccountId(Data7BeneficiaryAccountId beneficiaryAccountId) {
        this.beneficiaryAccountId = beneficiaryAccountId;
    }

    /**
     * Getter for FromAmount.
     * Amount to send.
     * @return Returns the String
     */
    @JsonGetter("from_amount")
    public String getFromAmount() {
        return fromAmount;
    }

    /**
     * Setter for FromAmount.
     * Amount to send.
     * @param fromAmount Value for String
     */
    @JsonSetter("from_amount")
    public void setFromAmount(String fromAmount) {
        this.fromAmount = fromAmount;
    }

    /**
     * Getter for FromCurrency.
     * Source currency code.
     * @return Returns the String
     */
    @JsonGetter("from_currency")
    public String getFromCurrency() {
        return fromCurrency;
    }

    /**
     * Setter for FromCurrency.
     * Source currency code.
     * @param fromCurrency Value for String
     */
    @JsonSetter("from_currency")
    public void setFromCurrency(String fromCurrency) {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Getter for FromNetwork.
     * Source blockchain network.
     * @return Returns the Data7FromNetwork
     */
    @JsonGetter("from_network")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7FromNetwork getFromNetwork() {
        return fromNetwork;
    }

    /**
     * Setter for FromNetwork.
     * Source blockchain network.
     * @param fromNetwork Value for Data7FromNetwork
     */
    @JsonSetter("from_network")
    public void setFromNetwork(Data7FromNetwork fromNetwork) {
        this.fromNetwork = fromNetwork;
    }

    /**
     * Getter for ToAmount.
     * Amount to receive.
     * @return Returns the String
     */
    @JsonGetter("to_amount")
    public String getToAmount() {
        return toAmount;
    }

    /**
     * Setter for ToAmount.
     * Amount to receive.
     * @param toAmount Value for String
     */
    @JsonSetter("to_amount")
    public void setToAmount(String toAmount) {
        this.toAmount = toAmount;
    }

    /**
     * Getter for ToCurrency.
     * Destination currency code.
     * @return Returns the String
     */
    @JsonGetter("to_currency")
    public String getToCurrency() {
        return toCurrency;
    }

    /**
     * Setter for ToCurrency.
     * Destination currency code.
     * @param toCurrency Value for String
     */
    @JsonSetter("to_currency")
    public void setToCurrency(String toCurrency) {
        this.toCurrency = toCurrency;
    }

    /**
     * Getter for ToNetwork.
     * Destination blockchain network.
     * @return Returns the Data7ToNetwork
     */
    @JsonGetter("to_network")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7ToNetwork getToNetwork() {
        return toNetwork;
    }

    /**
     * Setter for ToNetwork.
     * Destination blockchain network.
     * @param toNetwork Value for Data7ToNetwork
     */
    @JsonSetter("to_network")
    public void setToNetwork(Data7ToNetwork toNetwork) {
        this.toNetwork = toNetwork;
    }

    /**
     * Getter for RiskStatus.
     * Current risk status.
     * @return Returns the RiskStatusEnum
     */
    @JsonGetter("risk_status")
    public RiskStatusEnum getRiskStatus() {
        return riskStatus;
    }

    /**
     * Setter for RiskStatus.
     * Current risk status.
     * @param riskStatus Value for RiskStatusEnum
     */
    @JsonSetter("risk_status")
    public void setRiskStatus(RiskStatusEnum riskStatus) {
        this.riskStatus = riskStatus;
    }

    /**
     * Getter for RiskStatusReasons.
     * List of reasons for risk status.
     * @return Returns the Data7RiskStatusReasons
     */
    @JsonGetter("risk_status_reasons")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7RiskStatusReasons getRiskStatusReasons() {
        return riskStatusReasons;
    }

    /**
     * Setter for RiskStatusReasons.
     * List of reasons for risk status.
     * @param riskStatusReasons Value for Data7RiskStatusReasons
     */
    @JsonSetter("risk_status_reasons")
    public void setRiskStatusReasons(Data7RiskStatusReasons riskStatusReasons) {
        this.riskStatusReasons = riskStatusReasons;
    }

    /**
     * Getter for RiskReviewedBy.
     * ID of the user who performed the risk review.
     * @return Returns the Data7RiskReviewedBy
     */
    @JsonGetter("risk_reviewed_by")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7RiskReviewedBy getRiskReviewedBy() {
        return riskReviewedBy;
    }

    /**
     * Setter for RiskReviewedBy.
     * ID of the user who performed the risk review.
     * @param riskReviewedBy Value for Data7RiskReviewedBy
     */
    @JsonSetter("risk_reviewed_by")
    public void setRiskReviewedBy(Data7RiskReviewedBy riskReviewedBy) {
        this.riskReviewedBy = riskReviewedBy;
    }

    /**
     * Getter for RiskReviewedAt.
     * Timestamp of risk review.
     * @return Returns the Data7RiskReviewedAt
     */
    @JsonGetter("risk_reviewed_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7RiskReviewedAt getRiskReviewedAt() {
        return riskReviewedAt;
    }

    /**
     * Setter for RiskReviewedAt.
     * Timestamp of risk review.
     * @param riskReviewedAt Value for Data7RiskReviewedAt
     */
    @JsonSetter("risk_reviewed_at")
    public void setRiskReviewedAt(Data7RiskReviewedAt riskReviewedAt) {
        this.riskReviewedAt = riskReviewedAt;
    }

    /**
     * Getter for BalanceStatus.
     * Balance reservation status.
     * @return Returns the Data7BalanceStatus
     */
    @JsonGetter("balance_status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7BalanceStatus getBalanceStatus() {
        return balanceStatus;
    }

    /**
     * Setter for BalanceStatus.
     * Balance reservation status.
     * @param balanceStatus Value for Data7BalanceStatus
     */
    @JsonSetter("balance_status")
    public void setBalanceStatus(Data7BalanceStatus balanceStatus) {
        this.balanceStatus = balanceStatus;
    }

    /**
     * Getter for BalanceReservedAt.
     * Timestamp when balance was reserved.
     * @return Returns the Data7BalanceReservedAt
     */
    @JsonGetter("balance_reserved_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7BalanceReservedAt getBalanceReservedAt() {
        return balanceReservedAt;
    }

    /**
     * Setter for BalanceReservedAt.
     * Timestamp when balance was reserved.
     * @param balanceReservedAt Value for Data7BalanceReservedAt
     */
    @JsonSetter("balance_reserved_at")
    public void setBalanceReservedAt(Data7BalanceReservedAt balanceReservedAt) {
        this.balanceReservedAt = balanceReservedAt;
    }

    /**
     * Getter for Steps.
     * Optional list of system-generated steps that make up this payment/transfer route.
     * @return Returns the List of Step
     */
    @JsonGetter("steps")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Step> getSteps() {
        return steps;
    }

    /**
     * Setter for Steps.
     * Optional list of system-generated steps that make up this payment/transfer route.
     * @param steps Value for List of Step
     */
    @JsonSetter("steps")
    public void setSteps(List<Step> steps) {
        this.steps = steps;
    }

    /**
     * Getter for CreatedAt.
     * ISO 8601 timestamp of creation.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * ISO 8601 timestamp of creation.
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * ISO 8601 timestamp of last update.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updated_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * ISO 8601 timestamp of last update.
     * @param updatedAt Value for LocalDateTime
     */
    @JsonSetter("updated_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for ExpiresAt.
     * ISO 8601 timestamp when the quote expires.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("expires_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    /**
     * Setter for ExpiresAt.
     * ISO 8601 timestamp when the quote expires.
     * @param expiresAt Value for LocalDateTime
     */
    @JsonSetter("expires_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Converts this Data7 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data7 [" + "id=" + id + ", workspaceId=" + workspaceId + ", direction=" + direction
                + ", paymentType=" + paymentType + ", fromAmount=" + fromAmount + ", fromCurrency="
                + fromCurrency + ", toAmount=" + toAmount + ", toCurrency=" + toCurrency
                + ", riskStatus=" + riskStatus + ", createdAt=" + createdAt + ", updatedAt="
                + updatedAt + ", expiresAt=" + expiresAt + ", organizationReferenceId="
                + organizationReferenceId + ", sourceAccountId=" + sourceAccountId
                + ", originatorAccountId=" + originatorAccountId + ", beneficiaryAccountId="
                + beneficiaryAccountId + ", fromNetwork=" + fromNetwork + ", toNetwork=" + toNetwork
                + ", riskStatusReasons=" + riskStatusReasons + ", riskReviewedBy=" + riskReviewedBy
                + ", riskReviewedAt=" + riskReviewedAt + ", balanceStatus=" + balanceStatus
                + ", balanceReservedAt=" + balanceReservedAt + ", steps=" + steps + "]";
    }

    /**
     * Builds a new {@link Data7.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data7.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, workspaceId, direction, paymentType, fromAmount,
                fromCurrency, toAmount, toCurrency, riskStatus, createdAt, updatedAt, expiresAt)
                .organizationReferenceId(getOrganizationReferenceId())
                .sourceAccountId(getSourceAccountId())
                .originatorAccountId(getOriginatorAccountId())
                .beneficiaryAccountId(getBeneficiaryAccountId())
                .fromNetwork(getFromNetwork())
                .toNetwork(getToNetwork())
                .riskStatusReasons(getRiskStatusReasons())
                .riskReviewedBy(getRiskReviewedBy())
                .riskReviewedAt(getRiskReviewedAt())
                .balanceStatus(getBalanceStatus())
                .balanceReservedAt(getBalanceReservedAt())
                .steps(getSteps());
        return builder;
    }

    /**
     * Class to build instances of {@link Data7}.
     */
    public static class Builder {
        private String id;
        private String workspaceId;
        private Direction1Enum direction;
        private PaymentTypeEnum paymentType;
        private String fromAmount;
        private String fromCurrency;
        private String toAmount;
        private String toCurrency;
        private RiskStatusEnum riskStatus;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
        private LocalDateTime expiresAt;
        private Data7OrganizationReferenceId organizationReferenceId;
        private Data7SourceAccountId sourceAccountId;
        private Data7OriginatorAccountId originatorAccountId;
        private Data7BeneficiaryAccountId beneficiaryAccountId;
        private Data7FromNetwork fromNetwork;
        private Data7ToNetwork toNetwork;
        private Data7RiskStatusReasons riskStatusReasons;
        private Data7RiskReviewedBy riskReviewedBy;
        private Data7RiskReviewedAt riskReviewedAt;
        private Data7BalanceStatus balanceStatus;
        private Data7BalanceReservedAt balanceReservedAt;
        private List<Step> steps;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  workspaceId  String value for workspaceId.
         * @param  direction  Direction1Enum value for direction.
         * @param  paymentType  PaymentTypeEnum value for paymentType.
         * @param  fromAmount  String value for fromAmount.
         * @param  fromCurrency  String value for fromCurrency.
         * @param  toAmount  String value for toAmount.
         * @param  toCurrency  String value for toCurrency.
         * @param  riskStatus  RiskStatusEnum value for riskStatus.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @param  updatedAt  LocalDateTime value for updatedAt.
         * @param  expiresAt  LocalDateTime value for expiresAt.
         */
        public Builder(String id, String workspaceId, Direction1Enum direction,
                PaymentTypeEnum paymentType, String fromAmount, String fromCurrency,
                String toAmount, String toCurrency, RiskStatusEnum riskStatus,
                LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime expiresAt) {
            this.id = id;
            this.workspaceId = workspaceId;
            this.direction = direction;
            this.paymentType = paymentType;
            this.fromAmount = fromAmount;
            this.fromCurrency = fromCurrency;
            this.toAmount = toAmount;
            this.toCurrency = toCurrency;
            this.riskStatus = riskStatus;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
            this.expiresAt = expiresAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for direction.
         * @param  direction  Direction1Enum value for direction.
         * @return Builder
         */
        public Builder direction(Direction1Enum direction) {
            this.direction = direction;
            return this;
        }

        /**
         * Setter for paymentType.
         * @param  paymentType  PaymentTypeEnum value for paymentType.
         * @return Builder
         */
        public Builder paymentType(PaymentTypeEnum paymentType) {
            this.paymentType = paymentType;
            return this;
        }

        /**
         * Setter for fromAmount.
         * @param  fromAmount  String value for fromAmount.
         * @return Builder
         */
        public Builder fromAmount(String fromAmount) {
            this.fromAmount = fromAmount;
            return this;
        }

        /**
         * Setter for fromCurrency.
         * @param  fromCurrency  String value for fromCurrency.
         * @return Builder
         */
        public Builder fromCurrency(String fromCurrency) {
            this.fromCurrency = fromCurrency;
            return this;
        }

        /**
         * Setter for toAmount.
         * @param  toAmount  String value for toAmount.
         * @return Builder
         */
        public Builder toAmount(String toAmount) {
            this.toAmount = toAmount;
            return this;
        }

        /**
         * Setter for toCurrency.
         * @param  toCurrency  String value for toCurrency.
         * @return Builder
         */
        public Builder toCurrency(String toCurrency) {
            this.toCurrency = toCurrency;
            return this;
        }

        /**
         * Setter for riskStatus.
         * @param  riskStatus  RiskStatusEnum value for riskStatus.
         * @return Builder
         */
        public Builder riskStatus(RiskStatusEnum riskStatus) {
            this.riskStatus = riskStatus;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  LocalDateTime value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for expiresAt.
         * @param  expiresAt  LocalDateTime value for expiresAt.
         * @return Builder
         */
        public Builder expiresAt(LocalDateTime expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * Setter for organizationReferenceId.
         * @param  organizationReferenceId  Data7OrganizationReferenceId value for
         *         organizationReferenceId.
         * @return Builder
         */
        public Builder organizationReferenceId(
                Data7OrganizationReferenceId organizationReferenceId) {
            this.organizationReferenceId = organizationReferenceId;
            return this;
        }

        /**
         * Setter for sourceAccountId.
         * @param  sourceAccountId  Data7SourceAccountId value for sourceAccountId.
         * @return Builder
         */
        public Builder sourceAccountId(Data7SourceAccountId sourceAccountId) {
            this.sourceAccountId = sourceAccountId;
            return this;
        }

        /**
         * Setter for originatorAccountId.
         * @param  originatorAccountId  Data7OriginatorAccountId value for originatorAccountId.
         * @return Builder
         */
        public Builder originatorAccountId(Data7OriginatorAccountId originatorAccountId) {
            this.originatorAccountId = originatorAccountId;
            return this;
        }

        /**
         * Setter for beneficiaryAccountId.
         * @param  beneficiaryAccountId  Data7BeneficiaryAccountId value for beneficiaryAccountId.
         * @return Builder
         */
        public Builder beneficiaryAccountId(Data7BeneficiaryAccountId beneficiaryAccountId) {
            this.beneficiaryAccountId = beneficiaryAccountId;
            return this;
        }

        /**
         * Setter for fromNetwork.
         * @param  fromNetwork  Data7FromNetwork value for fromNetwork.
         * @return Builder
         */
        public Builder fromNetwork(Data7FromNetwork fromNetwork) {
            this.fromNetwork = fromNetwork;
            return this;
        }

        /**
         * Setter for toNetwork.
         * @param  toNetwork  Data7ToNetwork value for toNetwork.
         * @return Builder
         */
        public Builder toNetwork(Data7ToNetwork toNetwork) {
            this.toNetwork = toNetwork;
            return this;
        }

        /**
         * Setter for riskStatusReasons.
         * @param  riskStatusReasons  Data7RiskStatusReasons value for riskStatusReasons.
         * @return Builder
         */
        public Builder riskStatusReasons(Data7RiskStatusReasons riskStatusReasons) {
            this.riskStatusReasons = riskStatusReasons;
            return this;
        }

        /**
         * Setter for riskReviewedBy.
         * @param  riskReviewedBy  Data7RiskReviewedBy value for riskReviewedBy.
         * @return Builder
         */
        public Builder riskReviewedBy(Data7RiskReviewedBy riskReviewedBy) {
            this.riskReviewedBy = riskReviewedBy;
            return this;
        }

        /**
         * Setter for riskReviewedAt.
         * @param  riskReviewedAt  Data7RiskReviewedAt value for riskReviewedAt.
         * @return Builder
         */
        public Builder riskReviewedAt(Data7RiskReviewedAt riskReviewedAt) {
            this.riskReviewedAt = riskReviewedAt;
            return this;
        }

        /**
         * Setter for balanceStatus.
         * @param  balanceStatus  Data7BalanceStatus value for balanceStatus.
         * @return Builder
         */
        public Builder balanceStatus(Data7BalanceStatus balanceStatus) {
            this.balanceStatus = balanceStatus;
            return this;
        }

        /**
         * Setter for balanceReservedAt.
         * @param  balanceReservedAt  Data7BalanceReservedAt value for balanceReservedAt.
         * @return Builder
         */
        public Builder balanceReservedAt(Data7BalanceReservedAt balanceReservedAt) {
            this.balanceReservedAt = balanceReservedAt;
            return this;
        }

        /**
         * Setter for steps.
         * @param  steps  List of Step value for steps.
         * @return Builder
         */
        public Builder steps(List<Step> steps) {
            this.steps = steps;
            return this;
        }

        /**
         * Builds a new {@link Data7} object using the set fields.
         * @return {@link Data7}
         */
        public Data7 build() {
            return new Data7(id, workspaceId, direction, paymentType, fromAmount, fromCurrency,
                    toAmount, toCurrency, riskStatus, createdAt, updatedAt, expiresAt,
                    organizationReferenceId, sourceAccountId, originatorAccountId,
                    beneficiaryAccountId, fromNetwork, toNetwork, riskStatusReasons, riskReviewedBy,
                    riskReviewedAt, balanceStatus, balanceReservedAt, steps);
        }
    }
}
