/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.FeeMetadata;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Fee type.
 */
public class Fee {
    private String feeAmount;
    private String feeCurrency;
    private String type;
    private FeeMetadata metadata;

    /**
     * Default constructor.
     */
    public Fee() {
    }

    /**
     * Initialization constructor.
     * @param  feeAmount  String value for feeAmount.
     * @param  feeCurrency  String value for feeCurrency.
     * @param  type  String value for type.
     * @param  metadata  FeeMetadata value for metadata.
     */
    public Fee(
            String feeAmount,
            String feeCurrency,
            String type,
            FeeMetadata metadata) {
        this.feeAmount = feeAmount;
        this.feeCurrency = feeCurrency;
        this.type = type;
        this.metadata = metadata;
    }

    /**
     * Getter for FeeAmount.
     * Fee amount.
     * @return Returns the String
     */
    @JsonGetter("fee_amount")
    public String getFeeAmount() {
        return feeAmount;
    }

    /**
     * Setter for FeeAmount.
     * Fee amount.
     * @param feeAmount Value for String
     */
    @JsonSetter("fee_amount")
    public void setFeeAmount(String feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * Getter for FeeCurrency.
     * Fee currency code.
     * @return Returns the String
     */
    @JsonGetter("fee_currency")
    public String getFeeCurrency() {
        return feeCurrency;
    }

    /**
     * Setter for FeeCurrency.
     * Fee currency code.
     * @param feeCurrency Value for String
     */
    @JsonSetter("fee_currency")
    public void setFeeCurrency(String feeCurrency) {
        this.feeCurrency = feeCurrency;
    }

    /**
     * Getter for Type.
     * Fee type (e.g., 'gas', 'provider').
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Fee type (e.g., 'gas', 'provider').
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Metadata.
     * Additional metadata for the fee.
     * @return Returns the FeeMetadata
     */
    @JsonGetter("metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FeeMetadata getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * Additional metadata for the fee.
     * @param metadata Value for FeeMetadata
     */
    @JsonSetter("metadata")
    public void setMetadata(FeeMetadata metadata) {
        this.metadata = metadata;
    }

    /**
     * Converts this Fee into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Fee [" + "feeAmount=" + feeAmount + ", feeCurrency=" + feeCurrency + ", type="
                + type + ", metadata=" + metadata + "]";
    }

    /**
     * Builds a new {@link Fee.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Fee.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(feeAmount, feeCurrency, type)
                .metadata(getMetadata());
        return builder;
    }

    /**
     * Class to build instances of {@link Fee}.
     */
    public static class Builder {
        private String feeAmount;
        private String feeCurrency;
        private String type;
        private FeeMetadata metadata;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  feeAmount  String value for feeAmount.
         * @param  feeCurrency  String value for feeCurrency.
         * @param  type  String value for type.
         */
        public Builder(String feeAmount, String feeCurrency, String type) {
            this.feeAmount = feeAmount;
            this.feeCurrency = feeCurrency;
            this.type = type;
        }

        /**
         * Setter for feeAmount.
         * @param  feeAmount  String value for feeAmount.
         * @return Builder
         */
        public Builder feeAmount(String feeAmount) {
            this.feeAmount = feeAmount;
            return this;
        }

        /**
         * Setter for feeCurrency.
         * @param  feeCurrency  String value for feeCurrency.
         * @return Builder
         */
        public Builder feeCurrency(String feeCurrency) {
            this.feeCurrency = feeCurrency;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  FeeMetadata value for metadata.
         * @return Builder
         */
        public Builder metadata(FeeMetadata metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Builds a new {@link Fee} object using the set fields.
         * @return {@link Fee}
         */
        public Fee build() {
            return new Fee(feeAmount, feeCurrency, type, metadata);
        }
    }
}
