/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for NetworksResponse type.
 */
public class NetworksResponse {
    private List<Network> data;

    /**
     * Default constructor.
     */
    public NetworksResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Network value for data.
     */
    public NetworksResponse(
            List<Network> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * List of all supported networks
     * @return Returns the List of Network
     */
    @JsonGetter("data")
    public List<Network> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * List of all supported networks
     * @param data Value for List of Network
     */
    @JsonSetter("data")
    public void setData(List<Network> data) {
        this.data = data;
    }

    /**
     * Converts this NetworksResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NetworksResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link NetworksResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NetworksResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link NetworksResponse}.
     */
    public static class Builder {
        private List<Network> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Network value for data.
         */
        public Builder(List<Network> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of Network value for data.
         * @return Builder
         */
        public Builder data(List<Network> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link NetworksResponse} object using the set fields.
         * @return {@link NetworksResponse}
         */
        public NetworksResponse build() {
            return new NetworksResponse(data);
        }
    }
}
