/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Pagination type.
 */
public class Pagination {
    private double page;
    private double limit;
    private double total;
    private double totalPages;
    private boolean hasNext;
    private boolean hasPrev;

    /**
     * Default constructor.
     */
    public Pagination() {
    }

    /**
     * Initialization constructor.
     * @param  page  double value for page.
     * @param  limit  double value for limit.
     * @param  total  double value for total.
     * @param  totalPages  double value for totalPages.
     * @param  hasNext  boolean value for hasNext.
     * @param  hasPrev  boolean value for hasPrev.
     */
    public Pagination(
            double page,
            double limit,
            double total,
            double totalPages,
            boolean hasNext,
            boolean hasPrev) {
        this.page = page;
        this.limit = limit;
        this.total = total;
        this.totalPages = totalPages;
        this.hasNext = hasNext;
        this.hasPrev = hasPrev;
    }

    /**
     * Getter for Page.
     * Current page number
     * @return Returns the double
     */
    @JsonGetter("page")
    public double getPage() {
        return page;
    }

    /**
     * Setter for Page.
     * Current page number
     * @param page Value for double
     */
    @JsonSetter("page")
    public void setPage(double page) {
        this.page = page;
    }

    /**
     * Getter for Limit.
     * Items per page
     * @return Returns the double
     */
    @JsonGetter("limit")
    public double getLimit() {
        return limit;
    }

    /**
     * Setter for Limit.
     * Items per page
     * @param limit Value for double
     */
    @JsonSetter("limit")
    public void setLimit(double limit) {
        this.limit = limit;
    }

    /**
     * Getter for Total.
     * Total number of items
     * @return Returns the double
     */
    @JsonGetter("total")
    public double getTotal() {
        return total;
    }

    /**
     * Setter for Total.
     * Total number of items
     * @param total Value for double
     */
    @JsonSetter("total")
    public void setTotal(double total) {
        this.total = total;
    }

    /**
     * Getter for TotalPages.
     * Total number of pages
     * @return Returns the double
     */
    @JsonGetter("total_pages")
    public double getTotalPages() {
        return totalPages;
    }

    /**
     * Setter for TotalPages.
     * Total number of pages
     * @param totalPages Value for double
     */
    @JsonSetter("total_pages")
    public void setTotalPages(double totalPages) {
        this.totalPages = totalPages;
    }

    /**
     * Getter for HasNext.
     * Has next page
     * @return Returns the boolean
     */
    @JsonGetter("has_next")
    public boolean getHasNext() {
        return hasNext;
    }

    /**
     * Setter for HasNext.
     * Has next page
     * @param hasNext Value for boolean
     */
    @JsonSetter("has_next")
    public void setHasNext(boolean hasNext) {
        this.hasNext = hasNext;
    }

    /**
     * Getter for HasPrev.
     * Has previous page
     * @return Returns the boolean
     */
    @JsonGetter("has_prev")
    public boolean getHasPrev() {
        return hasPrev;
    }

    /**
     * Setter for HasPrev.
     * Has previous page
     * @param hasPrev Value for boolean
     */
    @JsonSetter("has_prev")
    public void setHasPrev(boolean hasPrev) {
        this.hasPrev = hasPrev;
    }

    /**
     * Converts this Pagination into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Pagination [" + "page=" + page + ", limit=" + limit + ", total=" + total
                + ", totalPages=" + totalPages + ", hasNext=" + hasNext + ", hasPrev=" + hasPrev
                + "]";
    }

    /**
     * Builds a new {@link Pagination.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Pagination.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(page, limit, total, totalPages, hasNext, hasPrev);
        return builder;
    }

    /**
     * Class to build instances of {@link Pagination}.
     */
    public static class Builder {
        private double page;
        private double limit;
        private double total;
        private double totalPages;
        private boolean hasNext;
        private boolean hasPrev;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  page  double value for page.
         * @param  limit  double value for limit.
         * @param  total  double value for total.
         * @param  totalPages  double value for totalPages.
         * @param  hasNext  boolean value for hasNext.
         * @param  hasPrev  boolean value for hasPrev.
         */
        public Builder(double page, double limit, double total, double totalPages, boolean hasNext,
                boolean hasPrev) {
            this.page = page;
            this.limit = limit;
            this.total = total;
            this.totalPages = totalPages;
            this.hasNext = hasNext;
            this.hasPrev = hasPrev;
        }

        /**
         * Setter for page.
         * @param  page  double value for page.
         * @return Builder
         */
        public Builder page(double page) {
            this.page = page;
            return this;
        }

        /**
         * Setter for limit.
         * @param  limit  double value for limit.
         * @return Builder
         */
        public Builder limit(double limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Setter for total.
         * @param  total  double value for total.
         * @return Builder
         */
        public Builder total(double total) {
            this.total = total;
            return this;
        }

        /**
         * Setter for totalPages.
         * @param  totalPages  double value for totalPages.
         * @return Builder
         */
        public Builder totalPages(double totalPages) {
            this.totalPages = totalPages;
            return this;
        }

        /**
         * Setter for hasNext.
         * @param  hasNext  boolean value for hasNext.
         * @return Builder
         */
        public Builder hasNext(boolean hasNext) {
            this.hasNext = hasNext;
            return this;
        }

        /**
         * Setter for hasPrev.
         * @param  hasPrev  boolean value for hasPrev.
         * @return Builder
         */
        public Builder hasPrev(boolean hasPrev) {
            this.hasPrev = hasPrev;
            return this;
        }

        /**
         * Builds a new {@link Pagination} object using the set fields.
         * @return {@link Pagination}
         */
        public Pagination build() {
            return new Pagination(page, limit, total, totalPages, hasNext, hasPrev);
        }
    }
}
