/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PaymentListResponse type.
 */
public class PaymentListResponse {
    private List<Data7> data;
    private Pagination pagination;

    /**
     * Default constructor.
     */
    public PaymentListResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Data7 value for data.
     * @param  pagination  Pagination value for pagination.
     */
    public PaymentListResponse(
            List<Data7> data,
            Pagination pagination) {
        this.data = data;
        this.pagination = pagination;
    }

    /**
     * Getter for Data.
     * @return Returns the List of Data7
     */
    @JsonGetter("data")
    public List<Data7> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of Data7
     */
    @JsonSetter("data")
    public void setData(List<Data7> data) {
        this.data = data;
    }

    /**
     * Getter for Pagination.
     * Pagination details
     * @return Returns the Pagination
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * Pagination details
     * @param pagination Value for Pagination
     */
    @JsonSetter("pagination")
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Converts this PaymentListResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentListResponse [" + "data=" + data + ", pagination=" + pagination + "]";
    }

    /**
     * Builds a new {@link PaymentListResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaymentListResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data)
                .pagination(getPagination());
        return builder;
    }

    /**
     * Class to build instances of {@link PaymentListResponse}.
     */
    public static class Builder {
        private List<Data7> data;
        private Pagination pagination;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Data7 value for data.
         */
        public Builder(List<Data7> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of Data7 value for data.
         * @return Builder
         */
        public Builder data(List<Data7> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for pagination.
         * @param  pagination  Pagination value for pagination.
         * @return Builder
         */
        public Builder pagination(Pagination pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Builds a new {@link PaymentListResponse} object using the set fields.
         * @return {@link PaymentListResponse}
         */
        public PaymentListResponse build() {
            return new PaymentListResponse(data, pagination);
        }
    }
}
