/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Response type.
 */
public class Response {
    private String status;
    private String gitSha;
    private String env;

    /**
     * Default constructor.
     */
    public Response() {
    }

    /**
     * Initialization constructor.
     * @param  status  String value for status.
     * @param  gitSha  String value for gitSha.
     * @param  env  String value for env.
     */
    public Response(
            String status,
            String gitSha,
            String env) {
        this.status = status;
        this.gitSha = gitSha;
        this.env = env;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for GitSha.
     * @return Returns the String
     */
    @JsonGetter("gitSha")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGitSha() {
        return gitSha;
    }

    /**
     * Setter for GitSha.
     * @param gitSha Value for String
     */
    @JsonSetter("gitSha")
    public void setGitSha(String gitSha) {
        this.gitSha = gitSha;
    }

    /**
     * Getter for Env.
     * @return Returns the String
     */
    @JsonGetter("env")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEnv() {
        return env;
    }

    /**
     * Setter for Env.
     * @param env Value for String
     */
    @JsonSetter("env")
    public void setEnv(String env) {
        this.env = env;
    }

    /**
     * Converts this Response into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Response [" + "status=" + status + ", gitSha=" + gitSha + ", env=" + env + "]";
    }

    /**
     * Builds a new {@link Response.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Response.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .status(getStatus())
                .gitSha(getGitSha())
                .env(getEnv());
        return builder;
    }

    /**
     * Class to build instances of {@link Response}.
     */
    public static class Builder {
        private String status;
        private String gitSha;
        private String env;



        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for gitSha.
         * @param  gitSha  String value for gitSha.
         * @return Builder
         */
        public Builder gitSha(String gitSha) {
            this.gitSha = gitSha;
            return this;
        }

        /**
         * Setter for env.
         * @param  env  String value for env.
         * @return Builder
         */
        public Builder env(String env) {
            this.env = env;
            return this;
        }

        /**
         * Builds a new {@link Response} object using the set fields.
         * @return {@link Response}
         */
        public Response build() {
            return new Response(status, gitSha, env);
        }
    }
}
