/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * RiskStatusEnum to be used.
 */
public enum RiskStatusEnum {
    UNCHECKED,

    AWAITING_DECISION,

    APPROVED,

    REJECTED;


    private static TreeMap<String, RiskStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        UNCHECKED.value = "unchecked";
        AWAITING_DECISION.value = "awaiting_decision";
        APPROVED.value = "approved";
        REJECTED.value = "rejected";

        valueMap.put("unchecked", UNCHECKED);
        valueMap.put("awaiting_decision", AWAITING_DECISION);
        valueMap.put("approved", APPROVED);
        valueMap.put("rejected", REJECTED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static RiskStatusEnum constructFromString(String toConvert) throws IOException {
        RiskStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static RiskStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RiskStatusEnum values to list of string values.
     * @param toConvert The list of RiskStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<RiskStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (RiskStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 