/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessAddressCountry;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessCity;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessDba;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessLegalEntityIdentifier;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessLegalName;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessState;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessStreetAddress1;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantBusinessStreetAddress2;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantCountry;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TenantWebhookUrl;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Tenant type.
 */
public class Tenant {
    private String id;
    private String workspaceId;
    private TenantBusinessLegalName businessLegalName;
    private TenantBusinessDba businessDba;
    private TenantBusinessAddressCountry businessAddressCountry;
    private TenantBusinessStreetAddress1 businessStreetAddress1;
    private TenantBusinessStreetAddress2 businessStreetAddress2;
    private TenantBusinessCity businessCity;
    private TenantBusinessState businessState;
    private TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier;
    private TenantCountry country;
    private TenantWebhookUrl webhookUrl;
    private String createdAt;
    private String updatedAt;

    /**
     * Default constructor.
     */
    public Tenant() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  workspaceId  String value for workspaceId.
     * @param  businessLegalName  TenantBusinessLegalName value for businessLegalName.
     * @param  businessDba  TenantBusinessDba value for businessDba.
     * @param  businessAddressCountry  TenantBusinessAddressCountry value for
     *         businessAddressCountry.
     * @param  businessStreetAddress1  TenantBusinessStreetAddress1 value for
     *         businessStreetAddress1.
     * @param  businessStreetAddress2  TenantBusinessStreetAddress2 value for
     *         businessStreetAddress2.
     * @param  businessCity  TenantBusinessCity value for businessCity.
     * @param  businessState  TenantBusinessState value for businessState.
     * @param  businessLegalEntityIdentifier  TenantBusinessLegalEntityIdentifier value for
     *         businessLegalEntityIdentifier.
     * @param  country  TenantCountry value for country.
     * @param  webhookUrl  TenantWebhookUrl value for webhookUrl.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     */
    public Tenant(
            String id,
            String workspaceId,
            TenantBusinessLegalName businessLegalName,
            TenantBusinessDba businessDba,
            TenantBusinessAddressCountry businessAddressCountry,
            TenantBusinessStreetAddress1 businessStreetAddress1,
            TenantBusinessStreetAddress2 businessStreetAddress2,
            TenantBusinessCity businessCity,
            TenantBusinessState businessState,
            TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier,
            TenantCountry country,
            TenantWebhookUrl webhookUrl,
            String createdAt,
            String updatedAt) {
        this.id = id;
        this.workspaceId = workspaceId;
        this.businessLegalName = businessLegalName;
        this.businessDba = businessDba;
        this.businessAddressCountry = businessAddressCountry;
        this.businessStreetAddress1 = businessStreetAddress1;
        this.businessStreetAddress2 = businessStreetAddress2;
        this.businessCity = businessCity;
        this.businessState = businessState;
        this.businessLegalEntityIdentifier = businessLegalEntityIdentifier;
        this.country = country;
        this.webhookUrl = webhookUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for Id.
     * Unique identifier for the tenant
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for the tenant
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for WorkspaceId.
     * Workspace ID the tenant belongs to
     * @return Returns the String
     */
    @JsonGetter("workspace_id")
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Setter for WorkspaceId.
     * Workspace ID the tenant belongs to
     * @param workspaceId Value for String
     */
    @JsonSetter("workspace_id")
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for BusinessLegalName.
     * Legal business name
     * @return Returns the TenantBusinessLegalName
     */
    @JsonGetter("business_legal_name")
    public TenantBusinessLegalName getBusinessLegalName() {
        return businessLegalName;
    }

    /**
     * Setter for BusinessLegalName.
     * Legal business name
     * @param businessLegalName Value for TenantBusinessLegalName
     */
    @JsonSetter("business_legal_name")
    public void setBusinessLegalName(TenantBusinessLegalName businessLegalName) {
        this.businessLegalName = businessLegalName;
    }

    /**
     * Getter for BusinessDba.
     * DBA - Doing Business As
     * @return Returns the TenantBusinessDba
     */
    @JsonGetter("business_dba")
    public TenantBusinessDba getBusinessDba() {
        return businessDba;
    }

    /**
     * Setter for BusinessDba.
     * DBA - Doing Business As
     * @param businessDba Value for TenantBusinessDba
     */
    @JsonSetter("business_dba")
    public void setBusinessDba(TenantBusinessDba businessDba) {
        this.businessDba = businessDba;
    }

    /**
     * Getter for BusinessAddressCountry.
     * Country code in ISO 3166-1 format
     * @return Returns the TenantBusinessAddressCountry
     */
    @JsonGetter("business_address_country")
    public TenantBusinessAddressCountry getBusinessAddressCountry() {
        return businessAddressCountry;
    }

    /**
     * Setter for BusinessAddressCountry.
     * Country code in ISO 3166-1 format
     * @param businessAddressCountry Value for TenantBusinessAddressCountry
     */
    @JsonSetter("business_address_country")
    public void setBusinessAddressCountry(TenantBusinessAddressCountry businessAddressCountry) {
        this.businessAddressCountry = businessAddressCountry;
    }

    /**
     * Getter for BusinessStreetAddress1.
     * Street address line 1 (for businesses).
     * @return Returns the TenantBusinessStreetAddress1
     */
    @JsonGetter("business_street_address1")
    public TenantBusinessStreetAddress1 getBusinessStreetAddress1() {
        return businessStreetAddress1;
    }

    /**
     * Setter for BusinessStreetAddress1.
     * Street address line 1 (for businesses).
     * @param businessStreetAddress1 Value for TenantBusinessStreetAddress1
     */
    @JsonSetter("business_street_address1")
    public void setBusinessStreetAddress1(TenantBusinessStreetAddress1 businessStreetAddress1) {
        this.businessStreetAddress1 = businessStreetAddress1;
    }

    /**
     * Getter for BusinessStreetAddress2.
     * Street address line 2 (for businesses).
     * @return Returns the TenantBusinessStreetAddress2
     */
    @JsonGetter("business_street_address2")
    public TenantBusinessStreetAddress2 getBusinessStreetAddress2() {
        return businessStreetAddress2;
    }

    /**
     * Setter for BusinessStreetAddress2.
     * Street address line 2 (for businesses).
     * @param businessStreetAddress2 Value for TenantBusinessStreetAddress2
     */
    @JsonSetter("business_street_address2")
    public void setBusinessStreetAddress2(TenantBusinessStreetAddress2 businessStreetAddress2) {
        this.businessStreetAddress2 = businessStreetAddress2;
    }

    /**
     * Getter for BusinessCity.
     * City (for businesses).
     * @return Returns the TenantBusinessCity
     */
    @JsonGetter("business_city")
    public TenantBusinessCity getBusinessCity() {
        return businessCity;
    }

    /**
     * Setter for BusinessCity.
     * City (for businesses).
     * @param businessCity Value for TenantBusinessCity
     */
    @JsonSetter("business_city")
    public void setBusinessCity(TenantBusinessCity businessCity) {
        this.businessCity = businessCity;
    }

    /**
     * Getter for BusinessState.
     * State/region (for businesses).
     * @return Returns the TenantBusinessState
     */
    @JsonGetter("business_state")
    public TenantBusinessState getBusinessState() {
        return businessState;
    }

    /**
     * Setter for BusinessState.
     * State/region (for businesses).
     * @param businessState Value for TenantBusinessState
     */
    @JsonSetter("business_state")
    public void setBusinessState(TenantBusinessState businessState) {
        this.businessState = businessState;
    }

    /**
     * Getter for BusinessLegalEntityIdentifier.
     * Legal Entity Identifier (for businesses).
     * @return Returns the TenantBusinessLegalEntityIdentifier
     */
    @JsonGetter("business_legal_entity_identifier")
    public TenantBusinessLegalEntityIdentifier getBusinessLegalEntityIdentifier() {
        return businessLegalEntityIdentifier;
    }

    /**
     * Setter for BusinessLegalEntityIdentifier.
     * Legal Entity Identifier (for businesses).
     * @param businessLegalEntityIdentifier Value for TenantBusinessLegalEntityIdentifier
     */
    @JsonSetter("business_legal_entity_identifier")
    public void setBusinessLegalEntityIdentifier(TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier) {
        this.businessLegalEntityIdentifier = businessLegalEntityIdentifier;
    }

    /**
     * Getter for Country.
     * Country code derived from business address
     * @return Returns the TenantCountry
     */
    @JsonGetter("country")
    public TenantCountry getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * Country code derived from business address
     * @param country Value for TenantCountry
     */
    @JsonSetter("country")
    public void setCountry(TenantCountry country) {
        this.country = country;
    }

    /**
     * Getter for WebhookUrl.
     * Webhook URL for payment creation notifications
     * @return Returns the TenantWebhookUrl
     */
    @JsonGetter("webhook_url")
    public TenantWebhookUrl getWebhookUrl() {
        return webhookUrl;
    }

    /**
     * Setter for WebhookUrl.
     * Webhook URL for payment creation notifications
     * @param webhookUrl Value for TenantWebhookUrl
     */
    @JsonSetter("webhook_url")
    public void setWebhookUrl(TenantWebhookUrl webhookUrl) {
        this.webhookUrl = webhookUrl;
    }

    /**
     * Getter for CreatedAt.
     * Creation timestamp in ISO 8601 format
     * @return Returns the String
     */
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Creation timestamp in ISO 8601 format
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * Last update timestamp in ISO 8601 format
     * @return Returns the String
     */
    @JsonGetter("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * Last update timestamp in ISO 8601 format
     * @param updatedAt Value for String
     */
    @JsonSetter("updated_at")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Converts this Tenant into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Tenant [" + "id=" + id + ", workspaceId=" + workspaceId + ", businessLegalName="
                + businessLegalName + ", businessDba=" + businessDba + ", businessAddressCountry="
                + businessAddressCountry + ", businessStreetAddress1=" + businessStreetAddress1
                + ", businessStreetAddress2=" + businessStreetAddress2 + ", businessCity="
                + businessCity + ", businessState=" + businessState
                + ", businessLegalEntityIdentifier=" + businessLegalEntityIdentifier + ", country="
                + country + ", webhookUrl=" + webhookUrl + ", createdAt=" + createdAt
                + ", updatedAt=" + updatedAt + "]";
    }

    /**
     * Builds a new {@link Tenant.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Tenant.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, workspaceId, businessLegalName, businessDba,
                businessAddressCountry, businessStreetAddress1, businessStreetAddress2,
                businessCity, businessState, businessLegalEntityIdentifier, country, webhookUrl,
                createdAt, updatedAt);
        return builder;
    }

    /**
     * Class to build instances of {@link Tenant}.
     */
    public static class Builder {
        private String id;
        private String workspaceId;
        private TenantBusinessLegalName businessLegalName;
        private TenantBusinessDba businessDba;
        private TenantBusinessAddressCountry businessAddressCountry;
        private TenantBusinessStreetAddress1 businessStreetAddress1;
        private TenantBusinessStreetAddress2 businessStreetAddress2;
        private TenantBusinessCity businessCity;
        private TenantBusinessState businessState;
        private TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier;
        private TenantCountry country;
        private TenantWebhookUrl webhookUrl;
        private String createdAt;
        private String updatedAt;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  workspaceId  String value for workspaceId.
         * @param  businessLegalName  TenantBusinessLegalName value for businessLegalName.
         * @param  businessDba  TenantBusinessDba value for businessDba.
         * @param  businessAddressCountry  TenantBusinessAddressCountry value for
         *         businessAddressCountry.
         * @param  businessStreetAddress1  TenantBusinessStreetAddress1 value for
         *         businessStreetAddress1.
         * @param  businessStreetAddress2  TenantBusinessStreetAddress2 value for
         *         businessStreetAddress2.
         * @param  businessCity  TenantBusinessCity value for businessCity.
         * @param  businessState  TenantBusinessState value for businessState.
         * @param  businessLegalEntityIdentifier  TenantBusinessLegalEntityIdentifier value for
         *         businessLegalEntityIdentifier.
         * @param  country  TenantCountry value for country.
         * @param  webhookUrl  TenantWebhookUrl value for webhookUrl.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         */
        public Builder(String id, String workspaceId, TenantBusinessLegalName businessLegalName,
                TenantBusinessDba businessDba, TenantBusinessAddressCountry businessAddressCountry,
                TenantBusinessStreetAddress1 businessStreetAddress1,
                TenantBusinessStreetAddress2 businessStreetAddress2,
                TenantBusinessCity businessCity, TenantBusinessState businessState,
                TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier,
                TenantCountry country, TenantWebhookUrl webhookUrl, String createdAt,
                String updatedAt) {
            this.id = id;
            this.workspaceId = workspaceId;
            this.businessLegalName = businessLegalName;
            this.businessDba = businessDba;
            this.businessAddressCountry = businessAddressCountry;
            this.businessStreetAddress1 = businessStreetAddress1;
            this.businessStreetAddress2 = businessStreetAddress2;
            this.businessCity = businessCity;
            this.businessState = businessState;
            this.businessLegalEntityIdentifier = businessLegalEntityIdentifier;
            this.country = country;
            this.webhookUrl = webhookUrl;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for workspaceId.
         * @param  workspaceId  String value for workspaceId.
         * @return Builder
         */
        public Builder workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Setter for businessLegalName.
         * @param  businessLegalName  TenantBusinessLegalName value for businessLegalName.
         * @return Builder
         */
        public Builder businessLegalName(TenantBusinessLegalName businessLegalName) {
            this.businessLegalName = businessLegalName;
            return this;
        }

        /**
         * Setter for businessDba.
         * @param  businessDba  TenantBusinessDba value for businessDba.
         * @return Builder
         */
        public Builder businessDba(TenantBusinessDba businessDba) {
            this.businessDba = businessDba;
            return this;
        }

        /**
         * Setter for businessAddressCountry.
         * @param  businessAddressCountry  TenantBusinessAddressCountry value for
         *         businessAddressCountry.
         * @return Builder
         */
        public Builder businessAddressCountry(
                TenantBusinessAddressCountry businessAddressCountry) {
            this.businessAddressCountry = businessAddressCountry;
            return this;
        }

        /**
         * Setter for businessStreetAddress1.
         * @param  businessStreetAddress1  TenantBusinessStreetAddress1 value for
         *         businessStreetAddress1.
         * @return Builder
         */
        public Builder businessStreetAddress1(
                TenantBusinessStreetAddress1 businessStreetAddress1) {
            this.businessStreetAddress1 = businessStreetAddress1;
            return this;
        }

        /**
         * Setter for businessStreetAddress2.
         * @param  businessStreetAddress2  TenantBusinessStreetAddress2 value for
         *         businessStreetAddress2.
         * @return Builder
         */
        public Builder businessStreetAddress2(
                TenantBusinessStreetAddress2 businessStreetAddress2) {
            this.businessStreetAddress2 = businessStreetAddress2;
            return this;
        }

        /**
         * Setter for businessCity.
         * @param  businessCity  TenantBusinessCity value for businessCity.
         * @return Builder
         */
        public Builder businessCity(TenantBusinessCity businessCity) {
            this.businessCity = businessCity;
            return this;
        }

        /**
         * Setter for businessState.
         * @param  businessState  TenantBusinessState value for businessState.
         * @return Builder
         */
        public Builder businessState(TenantBusinessState businessState) {
            this.businessState = businessState;
            return this;
        }

        /**
         * Setter for businessLegalEntityIdentifier.
         * @param  businessLegalEntityIdentifier  TenantBusinessLegalEntityIdentifier value for
         *         businessLegalEntityIdentifier.
         * @return Builder
         */
        public Builder businessLegalEntityIdentifier(
                TenantBusinessLegalEntityIdentifier businessLegalEntityIdentifier) {
            this.businessLegalEntityIdentifier = businessLegalEntityIdentifier;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  TenantCountry value for country.
         * @return Builder
         */
        public Builder country(TenantCountry country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for webhookUrl.
         * @param  webhookUrl  TenantWebhookUrl value for webhookUrl.
         * @return Builder
         */
        public Builder webhookUrl(TenantWebhookUrl webhookUrl) {
            this.webhookUrl = webhookUrl;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Builds a new {@link Tenant} object using the set fields.
         * @return {@link Tenant}
         */
        public Tenant build() {
            return new Tenant(id, workspaceId, businessLegalName, businessDba,
                    businessAddressCountry, businessStreetAddress1, businessStreetAddress2,
                    businessCity, businessState, businessLegalEntityIdentifier, country, webhookUrl,
                    createdAt, updatedAt);
        }
    }
}
