/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for TenantListResponse type.
 */
public class TenantListResponse {
    private List<Tenant> data;

    /**
     * Default constructor.
     */
    public TenantListResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Tenant value for data.
     */
    public TenantListResponse(
            List<Tenant> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * List of tenants
     * @return Returns the List of Tenant
     */
    @JsonGetter("data")
    public List<Tenant> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * List of tenants
     * @param data Value for List of Tenant
     */
    @JsonSetter("data")
    public void setData(List<Tenant> data) {
        this.data = data;
    }

    /**
     * Converts this TenantListResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TenantListResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link TenantListResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TenantListResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link TenantListResponse}.
     */
    public static class Builder {
        private List<Tenant> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Tenant value for data.
         */
        public Builder(List<Tenant> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of Tenant value for data.
         * @return Builder
         */
        public Builder data(List<Tenant> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link TenantListResponse} object using the set fields.
         * @return {@link TenantListResponse}
         */
        public TenantListResponse build() {
            return new TenantListResponse(data);
        }
    }
}
