/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TenantApiCredentials type.
 */
public class TenantApiCredentials {
    private String clientId;
    private String clientSecret;
    private String tokenEndpoint;
    private String audience;

    /**
     * Default constructor.
     */
    public TenantApiCredentials() {
    }

    /**
     * Initialization constructor.
     * @param  clientId  String value for clientId.
     * @param  clientSecret  String value for clientSecret.
     * @param  tokenEndpoint  String value for tokenEndpoint.
     * @param  audience  String value for audience.
     */
    public TenantApiCredentials(
            String clientId,
            String clientSecret,
            String tokenEndpoint,
            String audience) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.tokenEndpoint = tokenEndpoint;
        this.audience = audience;
    }

    /**
     * Getter for ClientId.
     * Auth0 M2M Client ID
     * @return Returns the String
     */
    @JsonGetter("client_id")
    public String getClientId() {
        return clientId;
    }

    /**
     * Setter for ClientId.
     * Auth0 M2M Client ID
     * @param clientId Value for String
     */
    @JsonSetter("client_id")
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for ClientSecret.
     * Auth0 M2M Client Secret (only shown once!)
     * @return Returns the String
     */
    @JsonGetter("client_secret")
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * Setter for ClientSecret.
     * Auth0 M2M Client Secret (only shown once!)
     * @param clientSecret Value for String
     */
    @JsonSetter("client_secret")
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    /**
     * Getter for TokenEndpoint.
     * Auth0 token endpoint URL
     * @return Returns the String
     */
    @JsonGetter("token_endpoint")
    public String getTokenEndpoint() {
        return tokenEndpoint;
    }

    /**
     * Setter for TokenEndpoint.
     * Auth0 token endpoint URL
     * @param tokenEndpoint Value for String
     */
    @JsonSetter("token_endpoint")
    public void setTokenEndpoint(String tokenEndpoint) {
        this.tokenEndpoint = tokenEndpoint;
    }

    /**
     * Getter for Audience.
     * API audience for token requests
     * @return Returns the String
     */
    @JsonGetter("audience")
    public String getAudience() {
        return audience;
    }

    /**
     * Setter for Audience.
     * API audience for token requests
     * @param audience Value for String
     */
    @JsonSetter("audience")
    public void setAudience(String audience) {
        this.audience = audience;
    }

    /**
     * Converts this TenantApiCredentials into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TenantApiCredentials [" + "clientId=" + clientId + ", clientSecret=" + clientSecret
                + ", tokenEndpoint=" + tokenEndpoint + ", audience=" + audience + "]";
    }

    /**
     * Builds a new {@link TenantApiCredentials.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TenantApiCredentials.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(clientId, clientSecret, tokenEndpoint, audience);
        return builder;
    }

    /**
     * Class to build instances of {@link TenantApiCredentials}.
     */
    public static class Builder {
        private String clientId;
        private String clientSecret;
        private String tokenEndpoint;
        private String audience;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  clientId  String value for clientId.
         * @param  clientSecret  String value for clientSecret.
         * @param  tokenEndpoint  String value for tokenEndpoint.
         * @param  audience  String value for audience.
         */
        public Builder(String clientId, String clientSecret, String tokenEndpoint,
                String audience) {
            this.clientId = clientId;
            this.clientSecret = clientSecret;
            this.tokenEndpoint = tokenEndpoint;
            this.audience = audience;
        }

        /**
         * Setter for clientId.
         * @param  clientId  String value for clientId.
         * @return Builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Setter for clientSecret.
         * @param  clientSecret  String value for clientSecret.
         * @return Builder
         */
        public Builder clientSecret(String clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Setter for tokenEndpoint.
         * @param  tokenEndpoint  String value for tokenEndpoint.
         * @return Builder
         */
        public Builder tokenEndpoint(String tokenEndpoint) {
            this.tokenEndpoint = tokenEndpoint;
            return this;
        }

        /**
         * Setter for audience.
         * @param  audience  String value for audience.
         * @return Builder
         */
        public Builder audience(String audience) {
            this.audience = audience;
            return this;
        }

        /**
         * Builds a new {@link TenantApiCredentials} object using the set fields.
         * @return {@link TenantApiCredentials}
         */
        public TenantApiCredentials build() {
            return new TenantApiCredentials(clientId, clientSecret, tokenEndpoint, audience);
        }
    }
}
