/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import app.zuplo.tesserplatformv1pull51me98e48a7.DateTimeHelper;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepCompletedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepConfirmedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepFailedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepFinalizedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepFromAccountAssetId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepFromAccountId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepProviderKey;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepSubmittedAt;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepToAccountAssetId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepToAccountId;
import app.zuplo.tesserplatformv1pull51me98e48a7.models.containers.TransferStepTransactionHash;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.time.LocalDateTime;
import java.util.List;

/**
 * This is a model class for TransferStep type.
 */
public class TransferStep {
    private String id;
    private String transferId;
    private int stepSequence;
    private StepTypeEnum stepType;
    private TransferStepFromAccountAssetId fromAccountAssetId;
    private String fromAmount;
    private String fromCurrency;
    private TransferStepToAccountAssetId toAccountAssetId;
    private String toAmount;
    private String toCurrency;
    private TransferStepTransactionHash transactionHash;
    private List<Fee1> fees;
    private OptionalNullable<TransferStepProviderKey> providerKey;
    private StatusEnum status;
    private OptionalNullable<List<List<String>>> statusReasons;
    private TransferStepSubmittedAt submittedAt;
    private TransferStepConfirmedAt confirmedAt;
    private TransferStepFinalizedAt finalizedAt;
    private TransferStepCompletedAt completedAt;
    private TransferStepFailedAt failedAt;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private TransferStepFromAccountId fromAccountId;
    private TransferStepToAccountId toAccountId;

    /**
     * Default constructor.
     */
    public TransferStep() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  transferId  String value for transferId.
     * @param  stepSequence  int value for stepSequence.
     * @param  stepType  StepTypeEnum value for stepType.
     * @param  fromAmount  String value for fromAmount.
     * @param  fromCurrency  String value for fromCurrency.
     * @param  toAmount  String value for toAmount.
     * @param  toCurrency  String value for toCurrency.
     * @param  status  StatusEnum value for status.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  updatedAt  LocalDateTime value for updatedAt.
     * @param  fromAccountAssetId  TransferStepFromAccountAssetId value for fromAccountAssetId.
     * @param  toAccountAssetId  TransferStepToAccountAssetId value for toAccountAssetId.
     * @param  transactionHash  TransferStepTransactionHash value for transactionHash.
     * @param  fees  List of Fee1 value for fees.
     * @param  providerKey  TransferStepProviderKey value for providerKey.
     * @param  statusReasons  List of String value for statusReasons.
     * @param  submittedAt  TransferStepSubmittedAt value for submittedAt.
     * @param  confirmedAt  TransferStepConfirmedAt value for confirmedAt.
     * @param  finalizedAt  TransferStepFinalizedAt value for finalizedAt.
     * @param  completedAt  TransferStepCompletedAt value for completedAt.
     * @param  failedAt  TransferStepFailedAt value for failedAt.
     * @param  fromAccountId  TransferStepFromAccountId value for fromAccountId.
     * @param  toAccountId  TransferStepToAccountId value for toAccountId.
     */
    public TransferStep(
            String id,
            String transferId,
            int stepSequence,
            StepTypeEnum stepType,
            String fromAmount,
            String fromCurrency,
            String toAmount,
            String toCurrency,
            StatusEnum status,
            LocalDateTime createdAt,
            LocalDateTime updatedAt,
            TransferStepFromAccountAssetId fromAccountAssetId,
            TransferStepToAccountAssetId toAccountAssetId,
            TransferStepTransactionHash transactionHash,
            List<Fee1> fees,
            TransferStepProviderKey providerKey,
            List<List<String>> statusReasons,
            TransferStepSubmittedAt submittedAt,
            TransferStepConfirmedAt confirmedAt,
            TransferStepFinalizedAt finalizedAt,
            TransferStepCompletedAt completedAt,
            TransferStepFailedAt failedAt,
            TransferStepFromAccountId fromAccountId,
            TransferStepToAccountId toAccountId) {
        this.id = id;
        this.transferId = transferId;
        this.stepSequence = stepSequence;
        this.stepType = stepType;
        this.fromAccountAssetId = fromAccountAssetId;
        this.fromAmount = fromAmount;
        this.fromCurrency = fromCurrency;
        this.toAccountAssetId = toAccountAssetId;
        this.toAmount = toAmount;
        this.toCurrency = toCurrency;
        this.transactionHash = transactionHash;
        this.fees = fees;
        this.providerKey = OptionalNullable.of(providerKey);
        this.status = status;
        this.statusReasons = OptionalNullable.of(statusReasons);
        this.submittedAt = submittedAt;
        this.confirmedAt = confirmedAt;
        this.finalizedAt = finalizedAt;
        this.completedAt = completedAt;
        this.failedAt = failedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.fromAccountId = fromAccountId;
        this.toAccountId = toAccountId;
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  transferId  String value for transferId.
     * @param  stepSequence  int value for stepSequence.
     * @param  stepType  StepTypeEnum value for stepType.
     * @param  fromAmount  String value for fromAmount.
     * @param  fromCurrency  String value for fromCurrency.
     * @param  toAmount  String value for toAmount.
     * @param  toCurrency  String value for toCurrency.
     * @param  status  StatusEnum value for status.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  updatedAt  LocalDateTime value for updatedAt.
     * @param  fromAccountAssetId  TransferStepFromAccountAssetId value for fromAccountAssetId.
     * @param  toAccountAssetId  TransferStepToAccountAssetId value for toAccountAssetId.
     * @param  transactionHash  TransferStepTransactionHash value for transactionHash.
     * @param  fees  List of Fee1 value for fees.
     * @param  providerKey  TransferStepProviderKey value for providerKey.
     * @param  statusReasons  List of String value for statusReasons.
     * @param  submittedAt  TransferStepSubmittedAt value for submittedAt.
     * @param  confirmedAt  TransferStepConfirmedAt value for confirmedAt.
     * @param  finalizedAt  TransferStepFinalizedAt value for finalizedAt.
     * @param  completedAt  TransferStepCompletedAt value for completedAt.
     * @param  failedAt  TransferStepFailedAt value for failedAt.
     * @param  fromAccountId  TransferStepFromAccountId value for fromAccountId.
     * @param  toAccountId  TransferStepToAccountId value for toAccountId.
     */

    protected TransferStep(String id, String transferId, int stepSequence, StepTypeEnum stepType,
            String fromAmount, String fromCurrency, String toAmount, String toCurrency,
            StatusEnum status, LocalDateTime createdAt, LocalDateTime updatedAt,
            TransferStepFromAccountAssetId fromAccountAssetId,
            TransferStepToAccountAssetId toAccountAssetId,
            TransferStepTransactionHash transactionHash, List<Fee1> fees,
            OptionalNullable<TransferStepProviderKey> providerKey,
            OptionalNullable<List<List<String>>> statusReasons, TransferStepSubmittedAt submittedAt,
            TransferStepConfirmedAt confirmedAt, TransferStepFinalizedAt finalizedAt,
            TransferStepCompletedAt completedAt, TransferStepFailedAt failedAt,
            TransferStepFromAccountId fromAccountId, TransferStepToAccountId toAccountId) {
        this.id = id;
        this.transferId = transferId;
        this.stepSequence = stepSequence;
        this.stepType = stepType;
        this.fromAccountAssetId = fromAccountAssetId;
        this.fromAmount = fromAmount;
        this.fromCurrency = fromCurrency;
        this.toAccountAssetId = toAccountAssetId;
        this.toAmount = toAmount;
        this.toCurrency = toCurrency;
        this.transactionHash = transactionHash;
        this.fees = fees;
        this.providerKey = providerKey;
        this.status = status;
        this.statusReasons = statusReasons;
        this.submittedAt = submittedAt;
        this.confirmedAt = confirmedAt;
        this.finalizedAt = finalizedAt;
        this.completedAt = completedAt;
        this.failedAt = failedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.fromAccountId = fromAccountId;
        this.toAccountId = toAccountId;
    }

    /**
     * Getter for Id.
     * Unique identifier for the step.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for the step.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for TransferId.
     * ID of the parent payment/transfer.
     * @return Returns the String
     */
    @JsonGetter("transfer_id")
    public String getTransferId() {
        return transferId;
    }

    /**
     * Setter for TransferId.
     * ID of the parent payment/transfer.
     * @param transferId Value for String
     */
    @JsonSetter("transfer_id")
    public void setTransferId(String transferId) {
        this.transferId = transferId;
    }

    /**
     * Getter for StepSequence.
     * Step sequence number (0-based or 1-based).
     * @return Returns the int
     */
    @JsonGetter("step_sequence")
    public int getStepSequence() {
        return stepSequence;
    }

    /**
     * Setter for StepSequence.
     * Step sequence number (0-based or 1-based).
     * @param stepSequence Value for int
     */
    @JsonSetter("step_sequence")
    public void setStepSequence(int stepSequence) {
        this.stepSequence = stepSequence;
    }

    /**
     * Getter for StepType.
     * Step type: 'stablecoin_transfer', 'offramp', 'onramp', 'fiat_transfer'.
     * @return Returns the StepTypeEnum
     */
    @JsonGetter("step_type")
    public StepTypeEnum getStepType() {
        return stepType;
    }

    /**
     * Setter for StepType.
     * Step type: 'stablecoin_transfer', 'offramp', 'onramp', 'fiat_transfer'.
     * @param stepType Value for StepTypeEnum
     */
    @JsonSetter("step_type")
    public void setStepType(StepTypeEnum stepType) {
        this.stepType = stepType;
    }

    /**
     * Getter for FromAccountAssetId.
     * Source account asset ID for this step.
     * @return Returns the TransferStepFromAccountAssetId
     */
    @JsonGetter("from_account_asset_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepFromAccountAssetId getFromAccountAssetId() {
        return fromAccountAssetId;
    }

    /**
     * Setter for FromAccountAssetId.
     * Source account asset ID for this step.
     * @param fromAccountAssetId Value for TransferStepFromAccountAssetId
     */
    @JsonSetter("from_account_asset_id")
    public void setFromAccountAssetId(TransferStepFromAccountAssetId fromAccountAssetId) {
        this.fromAccountAssetId = fromAccountAssetId;
    }

    /**
     * Getter for FromAmount.
     * Amount sent in this step.
     * @return Returns the String
     */
    @JsonGetter("from_amount")
    public String getFromAmount() {
        return fromAmount;
    }

    /**
     * Setter for FromAmount.
     * Amount sent in this step.
     * @param fromAmount Value for String
     */
    @JsonSetter("from_amount")
    public void setFromAmount(String fromAmount) {
        this.fromAmount = fromAmount;
    }

    /**
     * Getter for FromCurrency.
     * Currency code sent in this step.
     * @return Returns the String
     */
    @JsonGetter("from_currency")
    public String getFromCurrency() {
        return fromCurrency;
    }

    /**
     * Setter for FromCurrency.
     * Currency code sent in this step.
     * @param fromCurrency Value for String
     */
    @JsonSetter("from_currency")
    public void setFromCurrency(String fromCurrency) {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Getter for ToAccountAssetId.
     * Destination account asset ID for this step.
     * @return Returns the TransferStepToAccountAssetId
     */
    @JsonGetter("to_account_asset_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepToAccountAssetId getToAccountAssetId() {
        return toAccountAssetId;
    }

    /**
     * Setter for ToAccountAssetId.
     * Destination account asset ID for this step.
     * @param toAccountAssetId Value for TransferStepToAccountAssetId
     */
    @JsonSetter("to_account_asset_id")
    public void setToAccountAssetId(TransferStepToAccountAssetId toAccountAssetId) {
        this.toAccountAssetId = toAccountAssetId;
    }

    /**
     * Getter for ToAmount.
     * Amount received in this step.
     * @return Returns the String
     */
    @JsonGetter("to_amount")
    public String getToAmount() {
        return toAmount;
    }

    /**
     * Setter for ToAmount.
     * Amount received in this step.
     * @param toAmount Value for String
     */
    @JsonSetter("to_amount")
    public void setToAmount(String toAmount) {
        this.toAmount = toAmount;
    }

    /**
     * Getter for ToCurrency.
     * Currency code received in this step.
     * @return Returns the String
     */
    @JsonGetter("to_currency")
    public String getToCurrency() {
        return toCurrency;
    }

    /**
     * Setter for ToCurrency.
     * Currency code received in this step.
     * @param toCurrency Value for String
     */
    @JsonSetter("to_currency")
    public void setToCurrency(String toCurrency) {
        this.toCurrency = toCurrency;
    }

    /**
     * Getter for TransactionHash.
     * Blockchain transaction hash (for crypto steps).
     * @return Returns the TransferStepTransactionHash
     */
    @JsonGetter("transaction_hash")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepTransactionHash getTransactionHash() {
        return transactionHash;
    }

    /**
     * Setter for TransactionHash.
     * Blockchain transaction hash (for crypto steps).
     * @param transactionHash Value for TransferStepTransactionHash
     */
    @JsonSetter("transaction_hash")
    public void setTransactionHash(TransferStepTransactionHash transactionHash) {
        this.transactionHash = transactionHash;
    }

    /**
     * Getter for Fees.
     * List of fees associated with this step.
     * @return Returns the List of Fee1
     */
    @JsonGetter("fees")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Fee1> getFees() {
        return fees;
    }

    /**
     * Setter for Fees.
     * List of fees associated with this step.
     * @param fees Value for List of Fee1
     */
    @JsonSetter("fees")
    public void setFees(List<Fee1> fees) {
        this.fees = fees;
    }

    /**
     * Internal Getter for ProviderKey.
     * Provider key used for this step (if applicable).
     * @return Returns the Internal TransferStepProviderKey
     */
    @JsonGetter("provider_key")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<TransferStepProviderKey> internalGetProviderKey() {
        return this.providerKey;
    }

    /**
     * Getter for ProviderKey.
     * Provider key used for this step (if applicable).
     * @return Returns the TransferStepProviderKey
     */
    public TransferStepProviderKey getProviderKey() {
        return OptionalNullable.getFrom(providerKey);
    }

    /**
     * Setter for ProviderKey.
     * Provider key used for this step (if applicable).
     * @param providerKey Value for TransferStepProviderKey
     */
    @JsonSetter("provider_key")
    public void setProviderKey(TransferStepProviderKey providerKey) {
        this.providerKey = OptionalNullable.of(providerKey);
    }

    /**
     * UnSetter for ProviderKey.
     * Provider key used for this step (if applicable).
     */
    public void unsetProviderKey() {
        providerKey = null;
    }

    /**
     * Getter for Status.
     * Step status: 'created', 'submitted', 'confirmed', 'finalized', 'failed'.
     * @return Returns the StatusEnum
     */
    @JsonGetter("status")
    public StatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Step status: 'created', 'submitted', 'confirmed', 'finalized', 'failed'.
     * @param status Value for StatusEnum
     */
    @JsonSetter("status")
    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    /**
     * Internal Getter for StatusReasons.
     * Array of reasons explaining the current status (if any).
     * @return Returns the Internal List of String
     */
    @JsonGetter("status_reasons")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<List<List<String>>> internalGetStatusReasons() {
        return this.statusReasons;
    }

    /**
     * Getter for StatusReasons.
     * Array of reasons explaining the current status (if any).
     * @return Returns the List of String
     */
    public List<List<String>> getStatusReasons() {
        return OptionalNullable.getFrom(statusReasons);
    }

    /**
     * Setter for StatusReasons.
     * Array of reasons explaining the current status (if any).
     * @param statusReasons Value for List of String
     */
    @JsonSetter("status_reasons")
    public void setStatusReasons(List<List<String>> statusReasons) {
        this.statusReasons = OptionalNullable.of(statusReasons);
    }

    /**
     * UnSetter for StatusReasons.
     * Array of reasons explaining the current status (if any).
     */
    public void unsetStatusReasons() {
        statusReasons = null;
    }

    /**
     * Getter for SubmittedAt.
     * Submitted timestamp.
     * @return Returns the TransferStepSubmittedAt
     */
    @JsonGetter("submitted_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepSubmittedAt getSubmittedAt() {
        return submittedAt;
    }

    /**
     * Setter for SubmittedAt.
     * Submitted timestamp.
     * @param submittedAt Value for TransferStepSubmittedAt
     */
    @JsonSetter("submitted_at")
    public void setSubmittedAt(TransferStepSubmittedAt submittedAt) {
        this.submittedAt = submittedAt;
    }

    /**
     * Getter for ConfirmedAt.
     * Confirmed timestamp.
     * @return Returns the TransferStepConfirmedAt
     */
    @JsonGetter("confirmed_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepConfirmedAt getConfirmedAt() {
        return confirmedAt;
    }

    /**
     * Setter for ConfirmedAt.
     * Confirmed timestamp.
     * @param confirmedAt Value for TransferStepConfirmedAt
     */
    @JsonSetter("confirmed_at")
    public void setConfirmedAt(TransferStepConfirmedAt confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    /**
     * Getter for FinalizedAt.
     * Finalized timestamp.
     * @return Returns the TransferStepFinalizedAt
     */
    @JsonGetter("finalized_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepFinalizedAt getFinalizedAt() {
        return finalizedAt;
    }

    /**
     * Setter for FinalizedAt.
     * Finalized timestamp.
     * @param finalizedAt Value for TransferStepFinalizedAt
     */
    @JsonSetter("finalized_at")
    public void setFinalizedAt(TransferStepFinalizedAt finalizedAt) {
        this.finalizedAt = finalizedAt;
    }

    /**
     * Getter for CompletedAt.
     * Completed timestamp.
     * @return Returns the TransferStepCompletedAt
     */
    @JsonGetter("completed_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepCompletedAt getCompletedAt() {
        return completedAt;
    }

    /**
     * Setter for CompletedAt.
     * Completed timestamp.
     * @param completedAt Value for TransferStepCompletedAt
     */
    @JsonSetter("completed_at")
    public void setCompletedAt(TransferStepCompletedAt completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for FailedAt.
     * Failed timestamp.
     * @return Returns the TransferStepFailedAt
     */
    @JsonGetter("failed_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepFailedAt getFailedAt() {
        return failedAt;
    }

    /**
     * Setter for FailedAt.
     * Failed timestamp.
     * @param failedAt Value for TransferStepFailedAt
     */
    @JsonSetter("failed_at")
    public void setFailedAt(TransferStepFailedAt failedAt) {
        this.failedAt = failedAt;
    }

    /**
     * Getter for CreatedAt.
     * ISO 8601 timestamp of creation.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * ISO 8601 timestamp of creation.
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * ISO 8601 timestamp of last update.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updated_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * ISO 8601 timestamp of last update.
     * @param updatedAt Value for LocalDateTime
     */
    @JsonSetter("updated_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for FromAccountId.
     * Source account ID for this step.
     * @return Returns the TransferStepFromAccountId
     */
    @JsonGetter("from_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepFromAccountId getFromAccountId() {
        return fromAccountId;
    }

    /**
     * Setter for FromAccountId.
     * Source account ID for this step.
     * @param fromAccountId Value for TransferStepFromAccountId
     */
    @JsonSetter("from_account_id")
    public void setFromAccountId(TransferStepFromAccountId fromAccountId) {
        this.fromAccountId = fromAccountId;
    }

    /**
     * Getter for ToAccountId.
     * Destination account ID for this step.
     * @return Returns the TransferStepToAccountId
     */
    @JsonGetter("to_account_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransferStepToAccountId getToAccountId() {
        return toAccountId;
    }

    /**
     * Setter for ToAccountId.
     * Destination account ID for this step.
     * @param toAccountId Value for TransferStepToAccountId
     */
    @JsonSetter("to_account_id")
    public void setToAccountId(TransferStepToAccountId toAccountId) {
        this.toAccountId = toAccountId;
    }

    /**
     * Converts this TransferStep into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TransferStep [" + "id=" + id + ", transferId=" + transferId + ", stepSequence="
                + stepSequence + ", stepType=" + stepType + ", fromAmount=" + fromAmount
                + ", fromCurrency=" + fromCurrency + ", toAmount=" + toAmount + ", toCurrency="
                + toCurrency + ", status=" + status + ", createdAt=" + createdAt + ", updatedAt="
                + updatedAt + ", fromAccountAssetId=" + fromAccountAssetId + ", toAccountAssetId="
                + toAccountAssetId + ", transactionHash=" + transactionHash + ", fees=" + fees
                + ", providerKey=" + providerKey + ", statusReasons=" + statusReasons
                + ", submittedAt=" + submittedAt + ", confirmedAt=" + confirmedAt + ", finalizedAt="
                + finalizedAt + ", completedAt=" + completedAt + ", failedAt=" + failedAt
                + ", fromAccountId=" + fromAccountId + ", toAccountId=" + toAccountId + "]";
    }

    /**
     * Builds a new {@link TransferStep.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TransferStep.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, transferId, stepSequence, stepType, fromAmount,
                fromCurrency, toAmount, toCurrency, status, createdAt, updatedAt)
                .fromAccountAssetId(getFromAccountAssetId())
                .toAccountAssetId(getToAccountAssetId())
                .transactionHash(getTransactionHash())
                .fees(getFees())
                .submittedAt(getSubmittedAt())
                .confirmedAt(getConfirmedAt())
                .finalizedAt(getFinalizedAt())
                .completedAt(getCompletedAt())
                .failedAt(getFailedAt())
                .fromAccountId(getFromAccountId())
                .toAccountId(getToAccountId());
        builder.providerKey = internalGetProviderKey();
        builder.statusReasons = internalGetStatusReasons();
        return builder;
    }

    /**
     * Class to build instances of {@link TransferStep}.
     */
    public static class Builder {
        private String id;
        private String transferId;
        private int stepSequence;
        private StepTypeEnum stepType;
        private String fromAmount;
        private String fromCurrency;
        private String toAmount;
        private String toCurrency;
        private StatusEnum status;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
        private TransferStepFromAccountAssetId fromAccountAssetId;
        private TransferStepToAccountAssetId toAccountAssetId;
        private TransferStepTransactionHash transactionHash;
        private List<Fee1> fees;
        private OptionalNullable<TransferStepProviderKey> providerKey;
        private OptionalNullable<List<List<String>>> statusReasons;
        private TransferStepSubmittedAt submittedAt;
        private TransferStepConfirmedAt confirmedAt;
        private TransferStepFinalizedAt finalizedAt;
        private TransferStepCompletedAt completedAt;
        private TransferStepFailedAt failedAt;
        private TransferStepFromAccountId fromAccountId;
        private TransferStepToAccountId toAccountId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  transferId  String value for transferId.
         * @param  stepSequence  int value for stepSequence.
         * @param  stepType  StepTypeEnum value for stepType.
         * @param  fromAmount  String value for fromAmount.
         * @param  fromCurrency  String value for fromCurrency.
         * @param  toAmount  String value for toAmount.
         * @param  toCurrency  String value for toCurrency.
         * @param  status  StatusEnum value for status.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @param  updatedAt  LocalDateTime value for updatedAt.
         */
        public Builder(String id, String transferId, int stepSequence, StepTypeEnum stepType,
                String fromAmount, String fromCurrency, String toAmount, String toCurrency,
                StatusEnum status, LocalDateTime createdAt, LocalDateTime updatedAt) {
            this.id = id;
            this.transferId = transferId;
            this.stepSequence = stepSequence;
            this.stepType = stepType;
            this.fromAmount = fromAmount;
            this.fromCurrency = fromCurrency;
            this.toAmount = toAmount;
            this.toCurrency = toCurrency;
            this.status = status;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for transferId.
         * @param  transferId  String value for transferId.
         * @return Builder
         */
        public Builder transferId(String transferId) {
            this.transferId = transferId;
            return this;
        }

        /**
         * Setter for stepSequence.
         * @param  stepSequence  int value for stepSequence.
         * @return Builder
         */
        public Builder stepSequence(int stepSequence) {
            this.stepSequence = stepSequence;
            return this;
        }

        /**
         * Setter for stepType.
         * @param  stepType  StepTypeEnum value for stepType.
         * @return Builder
         */
        public Builder stepType(StepTypeEnum stepType) {
            this.stepType = stepType;
            return this;
        }

        /**
         * Setter for fromAmount.
         * @param  fromAmount  String value for fromAmount.
         * @return Builder
         */
        public Builder fromAmount(String fromAmount) {
            this.fromAmount = fromAmount;
            return this;
        }

        /**
         * Setter for fromCurrency.
         * @param  fromCurrency  String value for fromCurrency.
         * @return Builder
         */
        public Builder fromCurrency(String fromCurrency) {
            this.fromCurrency = fromCurrency;
            return this;
        }

        /**
         * Setter for toAmount.
         * @param  toAmount  String value for toAmount.
         * @return Builder
         */
        public Builder toAmount(String toAmount) {
            this.toAmount = toAmount;
            return this;
        }

        /**
         * Setter for toCurrency.
         * @param  toCurrency  String value for toCurrency.
         * @return Builder
         */
        public Builder toCurrency(String toCurrency) {
            this.toCurrency = toCurrency;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  StatusEnum value for status.
         * @return Builder
         */
        public Builder status(StatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  LocalDateTime value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for fromAccountAssetId.
         * @param  fromAccountAssetId  TransferStepFromAccountAssetId value for fromAccountAssetId.
         * @return Builder
         */
        public Builder fromAccountAssetId(TransferStepFromAccountAssetId fromAccountAssetId) {
            this.fromAccountAssetId = fromAccountAssetId;
            return this;
        }

        /**
         * Setter for toAccountAssetId.
         * @param  toAccountAssetId  TransferStepToAccountAssetId value for toAccountAssetId.
         * @return Builder
         */
        public Builder toAccountAssetId(TransferStepToAccountAssetId toAccountAssetId) {
            this.toAccountAssetId = toAccountAssetId;
            return this;
        }

        /**
         * Setter for transactionHash.
         * @param  transactionHash  TransferStepTransactionHash value for transactionHash.
         * @return Builder
         */
        public Builder transactionHash(TransferStepTransactionHash transactionHash) {
            this.transactionHash = transactionHash;
            return this;
        }

        /**
         * Setter for fees.
         * @param  fees  List of Fee1 value for fees.
         * @return Builder
         */
        public Builder fees(List<Fee1> fees) {
            this.fees = fees;
            return this;
        }

        /**
         * Setter for providerKey.
         * @param  providerKey  TransferStepProviderKey value for providerKey.
         * @return Builder
         */
        public Builder providerKey(TransferStepProviderKey providerKey) {
            this.providerKey = OptionalNullable.of(providerKey);
            return this;
        }

        /**
         * UnSetter for providerKey.
         * @return Builder
         */
        public Builder unsetProviderKey() {
            providerKey = null;
            return this;
        }

        /**
         * Setter for statusReasons.
         * @param  statusReasons  List of String value for statusReasons.
         * @return Builder
         */
        public Builder statusReasons(List<List<String>> statusReasons) {
            this.statusReasons = OptionalNullable.of(statusReasons);
            return this;
        }

        /**
         * UnSetter for statusReasons.
         * @return Builder
         */
        public Builder unsetStatusReasons() {
            statusReasons = null;
            return this;
        }

        /**
         * Setter for submittedAt.
         * @param  submittedAt  TransferStepSubmittedAt value for submittedAt.
         * @return Builder
         */
        public Builder submittedAt(TransferStepSubmittedAt submittedAt) {
            this.submittedAt = submittedAt;
            return this;
        }

        /**
         * Setter for confirmedAt.
         * @param  confirmedAt  TransferStepConfirmedAt value for confirmedAt.
         * @return Builder
         */
        public Builder confirmedAt(TransferStepConfirmedAt confirmedAt) {
            this.confirmedAt = confirmedAt;
            return this;
        }

        /**
         * Setter for finalizedAt.
         * @param  finalizedAt  TransferStepFinalizedAt value for finalizedAt.
         * @return Builder
         */
        public Builder finalizedAt(TransferStepFinalizedAt finalizedAt) {
            this.finalizedAt = finalizedAt;
            return this;
        }

        /**
         * Setter for completedAt.
         * @param  completedAt  TransferStepCompletedAt value for completedAt.
         * @return Builder
         */
        public Builder completedAt(TransferStepCompletedAt completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * Setter for failedAt.
         * @param  failedAt  TransferStepFailedAt value for failedAt.
         * @return Builder
         */
        public Builder failedAt(TransferStepFailedAt failedAt) {
            this.failedAt = failedAt;
            return this;
        }

        /**
         * Setter for fromAccountId.
         * @param  fromAccountId  TransferStepFromAccountId value for fromAccountId.
         * @return Builder
         */
        public Builder fromAccountId(TransferStepFromAccountId fromAccountId) {
            this.fromAccountId = fromAccountId;
            return this;
        }

        /**
         * Setter for toAccountId.
         * @param  toAccountId  TransferStepToAccountId value for toAccountId.
         * @return Builder
         */
        public Builder toAccountId(TransferStepToAccountId toAccountId) {
            this.toAccountId = toAccountId;
            return this;
        }

        /**
         * Builds a new {@link TransferStep} object using the set fields.
         * @return {@link TransferStep}
         */
        public TransferStep build() {
            return new TransferStep(id, transferId, stepSequence, stepType, fromAmount,
                    fromCurrency, toAmount, toCurrency, status, createdAt, updatedAt,
                    fromAccountAssetId, toAccountAssetId, transactionHash, fees, providerKey,
                    statusReasons, submittedAt, confirmedAt, finalizedAt, completedAt, failedAt,
                    fromAccountId, toAccountId);
        }
    }
}
