/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Type4Enum to be used.
 */
public enum Type4Enum {
    FIAT_BANK,

    STABLECOIN_ETHEREUM,

    STABLECOIN_SOLANA,

    STABLECOIN_STELLAR;


    private static TreeMap<String, Type4Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        FIAT_BANK.value = "fiat_bank";
        STABLECOIN_ETHEREUM.value = "stablecoin_ethereum";
        STABLECOIN_SOLANA.value = "stablecoin_solana";
        STABLECOIN_STELLAR.value = "stablecoin_stellar";

        valueMap.put("fiat_bank", FIAT_BANK);
        valueMap.put("stablecoin_ethereum", STABLECOIN_ETHEREUM);
        valueMap.put("stablecoin_solana", STABLECOIN_SOLANA);
        valueMap.put("stablecoin_stellar", STABLECOIN_STELLAR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Type4Enum constructFromString(String toConvert) throws IOException {
        Type4Enum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Type4Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Type4Enum values to list of string values.
     * @param toConvert The list of Type4Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Type4Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Type4Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 