/*
 * TesserAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.zuplo.tesserplatformv1pull51me98e48a7.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UpdateTenantResponse type.
 */
public class UpdateTenantResponse {
    private Data8 data;

    /**
     * Default constructor.
     */
    public UpdateTenantResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data8 value for data.
     */
    public UpdateTenantResponse(
            Data8 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data8
     */
    @JsonGetter("data")
    public Data8 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data8
     */
    @JsonSetter("data")
    public void setData(Data8 data) {
        this.data = data;
    }

    /**
     * Converts this UpdateTenantResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateTenantResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link UpdateTenantResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateTenantResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateTenantResponse}.
     */
    public static class Builder {
        private Data8 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data8 value for data.
         */
        public Builder(Data8 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data8 value for data.
         * @return Builder
         */
        public Builder data(Data8 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link UpdateTenantResponse} object using the set fields.
         * @return {@link UpdateTenantResponse}
         */
        public UpdateTenantResponse build() {
            return new UpdateTenantResponse(data);
        }
    }
}
